### ISSUE TITLE
Identify broken on City and County Boundaries layer.

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#118]
Select some features.
Identify, click on map.

Select features still listed in Super Tab, Grid, and Map.  Identify results don't show up.

**Comment by theduckylittle** [comment]
Not getting this bug...

**Comment by klassenjs** [comment]
Ok, wrong bug... It looks like Identify is broken when the City and County Boundaries layer is on.

404 on examples/desktop/city.html.

**Comment by elil** [comment]
I got this bug earlier today too but clearing cache fixed it so some commit from today fixed this as well.
