### ISSUE TITLE
Source maps in production

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#120]
The source map: geomoose.min.js.map is a bunch of webpack URLs which don't map to anything outside a "grunt serve" environment.  Thus, in production (apache/nginx server) the browsers debuggers can't make use of this info.  As it is large, I wonder if we should consider omitting this file from the build or from the packages.

**Comment by klassenjs** [comment]
Not building it looks like it has negative implications for UglifyJS.

Not packaging it could be as simple as adding a line to .npmignore.

**Comment by theduckylittle** [comment]
i'm willing to omit it so long as we're being diligent about producing both the .min.js and the .js .

debug.html is meant to work with the debug/less minified version of the code and that goes a long way towards debugging issues not related to compilation.  And the source-map doesn't help with compilation related issues.

**Comment by klassenjs** [comment]
I think the UglifyJS case makes it worthwhile to build it, otherwise errors from the compile aren't traceable.

I don't think it helps after compile so we could add it to npmignore and make the packages (npm, ms4w zips) a lot smaller.

**Comment by theduckylittle** [comment]
Make it so!

**Comment by klassenjs** [comment]
PR #166
