### ISSUE TITLE
Improve "Search by Address" failure

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#139]
When a "Search by Address" fails, it seems to hang the app.  Failure should be improved with some message of no result found or similar.    

Also, what is an address to test that works?  Using 100 Main St only led to the failure case.

**Comment by theduckylittle** [comment]
I wasn't getting a true failure but I was using the "debug" version of the application and seeing an error on the error console.

That said, I did find and subsequently fix the bug.

**Comment by elil** [comment]
This is the same for me as above.  

I also still can't find an example address that works.

**Comment by theduckylittle** [comment]
Found the issue, it's a HTTP/HTTPS mixup issue which is why I wasn't seeing it.  If you've got the chance to see these in Developer Tools or Firebug it's super helpful to have more information before debugging.

**Comment by elil** [comment]
Oh yeah, I should have at least figbugged that, pretty obvious then.

**Comment by theduckylittle** [comment]
I was able to see the bug on demo.geomoose.org and now demo.geomoose.org appears to be working -- closing.

**Comment by elil** [comment]
Appears to work now
