### ISSUE TITLE
Add features from file (to Drawing and Markup)

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#140]
Adding features from file to the Drawing and Markup works in the case of three lines totally 12 vertices.  I tried on larger files (the parcels, etc) and it did not appear to work.  It also gave no appearance of error or anything else.  If a file doesn't load, there should be some message, not silence.  

As a side commentary, the description in the Catalog seems a little verbose: "The Drawing and Markup layer can be used to add user defined shapes to the map. "  Maybe that's appropriate in the demo though.

**Comment by theduckylittle** [comment]
Which file did you use Eli? Can you post a URL to an example GeoJson or KML file?

**Comment by elil** [comment]
These came from the parcels (in the 2.# line).  I converted them with QGIS 2.18.3 using the simple, right click shp in catalog, click save as...  So OGR underneath but I didn't bother to do it directly in OGR which sometimes produces better results.  

[test_parcels _kml.zip](https://github.com/geomoose/gm3/files/1081109/test_parcels._kml.zip)
[test_parcels_geojson.zip](https://github.com/geomoose/gm3/files/1081110/test_parcels_geojson.zip)

**Comment by theduckylittle** [comment]
I found out why...  the files you're trying to upload are in EPSG:26915.  The Upload assumes files are in 4326 and then projects that to the map coordinates.  It's noting to do with large files.  I fixed the projection issue and the files loaded up 100% fine.

**Comment by klassenjs** [comment]
So my read on this is it technically "works" but should inform the user when something went wrong rather than giving the appearance of silently failing.

**Comment by theduckylittle** [comment]
This is a specific case of garbage-in-garbage-out.
Dialog improvements need to be done but there's a lot of gotchas that make it a bigger project.  I have some thoughts on it but I'm always willing to examine someone elses PR. LOL

**Comment by elil** [comment]
I see that test_parcels_geojson.zip is EPSG:26915.  

test_parcels _kml.zip is 4326 (values like -93.0461247360058,44.5435302527502) and exhibits this problem. 

I tested with geojson in 4326 [test_parcels_4326.zip](https://github.com/geomoose/gm3/files/1090292/test_parcels_4326.zip) which seems to work.  It may lead to another enhancement issue asking that the outline of polygons not be the same color as the fill.  It makes adjacent polygons very difficult to use.

**Comment by theduckylittle** [comment]
I'm moving this to an enhancement.  I'd like to tag it with a priority that it'll get done faster than others but we don't have a way of sorting that right now.  I think the following would be good:
1. We need a progress bar of some sort.  The user,  right now, has no means by which they know if the file is actually loading.  Not a big deal when working locally but uploading a 10+ MB file over the wire takes a while.
2. A success/error set of messages and/or follow up dialog.  The user doesn't get a positive indication anything has happened right now.
3. Sniffing and error handling of input data better.  If the coordinates look to be out of bounds the application should throw up a warning.  Also, again, we should have better ways of catching errors as they come in and reporting those errors to the user.

**Comment by klassenjs** [comment]
Maybe we need to setup 3.0, 3.1, and future milestones.

**Comment by theduckylittle** [comment]
Milestones are now setup.

**Comment by theduckylittle** [comment]
@elil - if it's any solace, it's actually set differently and there is a bug in either openlayers or the mapbox-style converter that needs fixed.

**Comment by elil** [comment]
Ah, if there is an upstream issue, noting it here can help keep track.  (and keep me from continuously mentioning it. )

**Comment by elil** [comment]
4. Polygon outline should be different color than polygon fill is now fixed.  

1,2,3 from https://github.com/geomoose/gm3/issues/140#issuecomment-310060294 remains

**Comment by klassenjs** [comment]
What is left here is related to #29.
