### ISSUE TITLE
Scalebars are a little low

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#161]
Scalebars are a little low in firefox desktop 
![scalebars](https://user-images.githubusercontent.com/5263258/27492299-933c518a-57fa-11e7-95dd-593de1bfc8a1.png)

**Comment by klassenjs** [comment]
I haven't checked but it seems odd MapServer would place a scalebar half off the map.  Is this a map being cut off in GeoMoose?

**Comment by theduckylittle** [comment]
It's sorta the case that GeoMoose is cutting off the map but MapServer doesn't offer the ability to "offset" the scalebar position away from a gutter. Right now there's a 1-2px incursion of the "border" on top of the footer that is overlapping the scalebar.  Even if you look at the raw MapServer image you can see that it is very, very, very close to the bottom of the image (like 0px offset) and so it's very easy for it to get obfuscated.

Solutions include:
1. Remove the border + add a different background color to the footer to provide visual differentiation.
2. Ignore it. Hey! Developer favorite!
3. Patch MapServer -- this will have a competing time problem.

**Comment by klassenjs** [comment]
This looks like something that changed between MapServer 6 and MapServer 7.  

Below are images with the same mapfile and same parameters generated by MapServer 6 and MapServer 7.  The MapServer 6 ouput is less squished and has a reasonable margin to the image edge compared to the MapServer 7 output.

MapServer 6:
![mapserv6](https://user-images.githubusercontent.com/165622/27546257-ee17e5d8-5a57-11e7-85c6-cbaca55f74ab.png)


MapServer 7:
![mapserv7](https://user-images.githubusercontent.com/165622/27546262-f1157476-5a57-11e7-8f6c-99eb08e0043e.png)

**Comment by klassenjs** [comment]
1) Helps but doesn't completely solve it (just removed the border line CSS in Firebug/etc.) and it still looks clipped, but then again so does the MapServer 7 result.  Although this begs the question of if we have a CSS problem and need to reduce the size of the map by 1px or set a margin/padding/something on the map to get the inner height correct.  (This is where my knowledge of CSS breaks down).

2) Maybe, but I don't like things that look broken, even if it isn't "our fault".

3) Might be the right answer, but understand the time constraints (probably an easy fix, but I don't have time to deal with it right now either.)

**Comment by elil** [comment]
We could do 1. or 2. for now as well as put a 3.0.1 milestone on it.

**Comment by theduckylittle** [comment]
Looking through the mapserver code: 
- https://github.com/mapserver/mapserver/blob/branch-7-0/mapscale.c

You can see that the Margin/Offset is defined as a constant. The only way to change those offsets is to RECOMPILE mapserver.

**Comment by theduckylittle** [comment]
The patch looks simple enough, adding an "OFFSET" keyword to scalebar that takes the place of VMARGIN and HMARGIN.

**Comment by klassenjs** [comment]
So, if I understand this correctly, we don't think this is something that can or should be fixed in GeoMoose, but is a bug/enhancement in MapServer.

I don't think telling people to patch and rebuild MapServer is a practical solution for many of our users.

I am not sure how to administratively handle a "bug" that needs to be fixed upstream.

From the GeoMoose perspective it is a known issue, won't likely generate a pull request in GeoMoose (so is in a way a wont-fix, and also not tied to a particular GeoMoose release), yet we do as time allows wish to work with MapServer to hopefully get this fixed.

**Comment by elil** [comment]
Administratively, open a ticket in MapServer.  Put a link to that MapServer
ticket in the GeoMoose ticket.  Done.

If the status of the MapServer ticket changes, then the status of the
GeoMoose ticket can change too.

Eli

**Comment by theduckylittle** [comment]
Created a mapserver pull request to see where this goes.

**Comment by klassenjs** [comment]
The catch here is if/when the PR is accepted and we update scalebar*.map in gm3-demo-data it will put a new lower bound on MapServer version.  We need to make sure we coordinate this is documented (main docs and changelog) and coordinated with a MS4W release (and ideally DebianGIS).  I assume docker users will just deal with it (as our dockerfile builds MapServer master anyway).

**Comment by elil** [comment]
We could perhaps update scalebar*.map by adding it in commented out.  I don't see a reason to require this recent a version of MapServer (even if I personally want to use that more recent version).  

`# Starting in MapServer 7.##, an offset can be used to adjust the position of the scalebar.`
`# To use this uncomment below`
`#OFFSET`
`#  5 5`
`#END`

**Comment by theduckylittle** [comment]
As we're still waiting on MapServer to merge the PR, putting to 3.1.1.

**Comment by klassenjs** [comment]
Ditto to 3.2.1

**Comment by elil** [comment]
Counting this as documentation and closing.
