### ISSUE TITLE
Identify tool throws "msProjectRect(): Warning: degenerate rect" with demo

### ISSUE THREAD

**Issue by jmckenna** [geomoose/gm3#186]
Using GM3-beta and the demo data, when I click on the map (near center, see the blue dot in the screeshot below), a valid GetFeatureInfo response is returned, and displayed in the interface:

![gm3-identify](https://user-images.githubusercontent.com/1611709/28089542-c3c47b70-665f-11e7-83c9-5f07a2a3d950.PNG)

However Apache's error log has a new entry of:

```
[Tue Jul 11 17:34:55.203574 2017] [cgi:error] [pid 5336:tid 1124] [client 127.0.0.1:53627] AH01215: msProjectRect(): Warning: degenerate rect {-10372911.782304,5552631.343093,-10372911.782304,5552631.343093}\r: C:/ms4w/Apache/cgi-bin/mapserv.exe, referer: http://127.0.0.1/gm3/desktop/index.html
```

The full GetFeatureInfo request (taken from DeveloperTools) is:

```
http://127.0.0.1/cgi-bin/mapserv.exe?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=parcels&LAYERS=parcels&MAP=%2Fms4w%2Fapps%2Fgm3-demo-data%2F.%2Fdemo%2Fparcels%2Fparcels.map&FEATURE_COUNT=1000&INFO_FORMAT=application%2Fvnd.ogc.gml&X=50&Y=50&SRS=EPSG%3A3857&STYLES=&WIDTH=101&HEIGHT=101&BBOX=-10374841.817267751%2C5550701.308128572%2C-10370981.747339351%2C5554561.378056974
```

(if I execute that GetFeatureInfo request in my browser, another msProjectRect() warning is logged in the Apache error log)

The returned GML is valid:

```
<?xml version="1.0" encoding="UTF-8"?>

<msGMLOutput 
	 xmlns:gml="http://www.opengis.net/gml"
	 xmlns:xlink="http://www.w3.org/1999/xlink"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<parcels_layer>
	<gml:name>Parcel Polygons</gml:name>
		<parcels_feature>
			<gml:boundedBy>
				<gml:Box srsName="EPSG:3857">
					<gml:coordinates>-10373575.600936,5552244.247556 -10372450.177138,5553377.101004</gml:coordinates>
				</gml:Box>
			</gml:boundedBy>
			<COUNTY_ID>037</COUNTY_ID>
			<PIN>130260001175</PIN>
			<BLDG_NUM></BLDG_NUM>
			<PREFIX_DIR></PREFIX_DIR>
			<PREFIXTYPE></PREFIXTYPE>
			<STREETNAME></STREETNAME>
			<STREETTYPE></STREETTYPE>
			<SUFFIX_DIR></SUFFIX_DIR>
			<UNIT_INFO></UNIT_INFO>
			<CITY>EUREKA TWP</CITY>
			<CITY_USPS></CITY_USPS>
			<ZIP></ZIP>
			<ZIP4></ZIP4>
			<PLAT_NAME></PLAT_NAME>
			<BLOCK></BLOCK>
			<LOT></LOT>
			<ACRES_POLY>154.37</ACRES_POLY>
			<ACRES_DEED>0.00</ACRES_DEED>
			<USE1_DESC>AG</USE1_DESC>
			<USE2_DESC></USE2_DESC>
			<USE3_DESC></USE3_DESC>
			<USE4_DESC></USE4_DESC>
			<MULTI_USES>N</MULTI_USES>
			<LANDMARK></LANDMARK>
			<OWNER_NAME>Thaddeus Garcia</OWNER_NAME>
			<OWNER_MORE></OWNER_MORE>
			<OWN_ADD_L1>113 CHIPOLA AVE APT 1106</OWN_ADD_L1>
			<OWN_ADD_L2></OWN_ADD_L2>
			<OWN_ADD_L3>DELAND FL 32720</OWN_ADD_L3>
			<TAX_NAME></TAX_NAME>
			<TAX_ADD_L1></TAX_ADD_L1>
			<TAX_ADD_L2></TAX_ADD_L2>
			<TAX_ADD_L3></TAX_ADD_L3>
			<HOMESTEAD>N</HOMESTEAD>
			<EMV_LAND>1178700</EMV_LAND>
			<EMV_BLDG>0</EMV_BLDG>
			<EMV_TOTAL>1178700</EMV_TOTAL>
			<TAX_CAPAC>4431</TAX_CAPAC>
			<TOTAL_TAX>3486</TOTAL_TAX>
			<SPEC_ASSES>0</SPEC_ASSES>
			<TAX_EXEMPT>N</TAX_EXEMPT>
			<XUSE1_DESC></XUSE1_DESC>
			<XUSE2_DESC></XUSE2_DESC>
			<XUSE3_DESC></XUSE3_DESC>
			<XUSE4_DESC></XUSE4_DESC>
			<DWELL_TYPE></DWELL_TYPE>
			<HOME_STYLE></HOME_STYLE>
			<FIN_SQ_FT>0</FIN_SQ_FT>
			<GARAGE></GARAGE>
			<GARAGESQFT></GARAGESQFT>
			<BASEMENT></BASEMENT>
			<HEATING></HEATING>
			<COOLING></COOLING>
			<YEAR_BUILT>0</YEAR_BUILT>
			<NUM_UNITS>0</NUM_UNITS>
			<SALE_DATE></SALE_DATE>
			<SALE_VALUE>0</SALE_VALUE>
			<SCHOOL_DST>659</SCHOOL_DST>
			<WSHD_DIST>NORTH CANNON RIVER</WSHD_DIST>
			<GREEN_ACRE>Y</GREEN_ACRE>
			<OPEN_SPACE>N</OPEN_SPACE>
			<AG_PRESERV>N</AG_PRESERV>
			<AGPRE_ENRD></AGPRE_ENRD>
			<AGPRE_EXPD></AGPRE_EXPD>
			<PARC_CODE>1</PARC_CODE>
		</parcels_feature>
	</parcels_layer>
</msGMLOutput>
```

**Comment by jmckenna** [comment]
I should also note that this is with the MapServer 7.0.6 release on Windows.

**Comment by theduckylittle** [comment]
Just as an aside: I'm *not* seeing this same bug using the same request on MapServer 7.0.6 on Debian Linux.

**Comment by theduckylittle** [comment]
I'm removing the 3.0.0 marker on this because it's another MapServer bug and I should write a test case for them.  What's happening is that the point-in-polygon search is being given a tolerance of 0.  MapServer is first doing a "query by rect" which takes the point + tolerance (0) and forms a rect.  Since the tolerance is set to 0 on a Polygon layer it will create a rect of 0 width -- which is degenerate.  An A:B test can be done by adding "TOLERANCE 1" to the parcels layer in parcels.map.

@klassenjs - Technically, we can silence the error message on Windows by adding TOLERANCE directives even to our polygon layers. But I feel like this would be a kludge.

**Comment by klassenjs** [comment]
That seems odd.  Why is the same version of MapServer behaving differently from Linux to Windows?

**Comment by theduckylittle** [comment]
I really don't know! I started testing on Linux and didn't see the error (using a modified version of Jeff's URL).  @jmckenna When compiling on windows do you change any of the default #define statements?

**Comment by klassenjs** [comment]
@theduckylittle I can confirm I am seeing the same thing as @jmckenna.  The returned GML looks correct.  The warning occurs in the Apache error.log on demo.geomoose.org (tested on Linux w/MapServer 7.0.4 and 7.0.6) when GETting the following URL:

https://demo.geomoose.org/cgi-bin/mapserv7?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=parcels&LAYERS=parcels&MAP=%2Fsrv%2Fdemo%2Fsrc%2F3.0%2Fgm3-demo-data%2F.%2Fdemo%2Fparcels%2Fparcels.map&FEATURE_COUNT=1000&INFO_FORMAT=application%2Fvnd.ogc.gml&X=50&Y=50&SRS=EPSG%3A3857&STYLES=&WIDTH=101&HEIGHT=101&BBOX=-10374841.817267751%2C5550701.308128572%2C-10370981.747339351%2C5554561.378056974

```
msProjectRect(): Warning: degenerate rect {-10372911.782304,5552631.343093,-10372911.782304,5552631.343093}
```

**Comment by theduckylittle** [comment]
@klassenjs Cool! Can you verify my hacky-fix? And/or should we be submitting a ticket to MapServer?

**Comment by klassenjs** [comment]
@theduckylittle I verify your hack.  M thoughts at the moment would be to leave gm3-demo-data alone and raise a MapServer ticket as:

1) GeoMoose appears to be sending a valid WMS request.
2) MapServer is returning a valid GML result (and thus from the user point of view things are working correctly).
3) MapServer is logging a warning not an error. 
4) We have a good understanding of what triggers the issue and so can make a useful bug report.

We might want to mention this in the docs as a known issue to allay the fears of an unsuspecting server admin who might stumble upon into it.

**Comment by jmckenna** [comment]
thanks guys, I agree that a MapServer ticket should be filed for this.

**Comment by jmckenna** [comment]
I also confirm that adding "TOLERANCE 1" in parcels.map solves this issue.  I am going to add that change to the MS4W GM3 package now.  I think you earlier said you were against this change, but, I would like to request that you make that change in the official demo package for GM3 (as who knows how long the MapServer ticket will remain open).  I think GM3 users will appreciate this.

**Comment by jmckenna** [comment]
the MS4W GM3 package now includes this tolerance change.

**Comment by theduckylittle** [comment]
I'm willing to close this as stale.
