### ISSUE TITLE
Support How-to Use a Basemap other than 3857

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/gm3#192]
Not everyone loves Web Mercator.  We should show how to use a projection other than it. 
This should include an updated how-to.

**Comment by klassenjs** [comment]
Note: This is more than a documentation issue.  

There are currently many places where 3857 is hard coded in the library:
* `upload.jsx` and `download.jsx`
* `printModal.jsx` and `geopdf.js` (as WKT)
* `mesaure.jsx`
* `application.jsx`
* `vector.jsx`
* `measure.jsx`
* `coordinates.jsx`

**Comment by chughes-lincoln** [comment]
I definitely think this would be useful, even if it's explaining how to modify these files and rebuild the geomoose javascript. Reprojecting data from our local coordinate to 3857 definitely slows things down in our build.

**Comment by klassenjs** [comment]
My biggest concern with 3857 is it really isn't appropriate for survey quality data.

**Comment by theduckylittle** [comment]
It's more a matter of OpenLayers. As you dig into the code it gets really ugly as you start changing up the projection. And in the years-gone-past we found people always wanted to bring in the open-tiled datasets and that was a real problem if they were serving in a local projection.
