### ISSUE TITLE
Identify and Map Sources using layer name "all"

### ISSUE THREAD

**Issue by mjreynolds** [geomoose/gm3#193]
In previous geomoose mapbooks we used a layer name = "all" which would ultimately result in all layers in the .map file turning on and off at the same time.  When the identify tool was used with one of these "all" layers, each .map layer template identify was run and all the .map layer results were returned.  Now it seems  with the identify template being configuring per layer in the mapbook mapsource section, we're not sure how to best address an "all" situation.

Note more recent mapserver versions actually required us to introduce use of the layer "group" parameter to our .map file where we set the value to "all".   This was done on every layer in the .map file.

Which direction should we head?

**Comment by theduckylittle** [comment]
Were the layers returning the same properties or were the feature types between the layers different?

**Comment by elil** [comment]
This could be discussed on the [email list](https://www.geomoose.org/info/mailing_lists.html) if you two want.  More people would potentially benefit from it and find it in the future as well.

**Comment by mjreynolds** [comment]
Each was different, unfortunately.  I think one option is to bootstrap (extend?) the identify service to intercept and perform a custom procedure.  We know we need this option for other purposes.

**Comment by theduckylittle** [comment]
I think you'll need to create a custom identify.js which has a different `query` method.  Which I think would look something close to this:

```javascript

var visible_layers = Application.getVisibleLayers();
var identify_layers = Application.getQueryableLayers({withTemplate: 'identify', requireVisible: false});
// this is a little bit dangerous of a suggestion as the react/internal geomoose api
// may change a bit over time.  I am open to adding an API method for this.
var map_sources = Application.store.getState().mapSources;

var query_layers = [];
for(var i = 0, ii = visible_layers.length; i < ii; i++) {
 var vis_path  = visible_layers[i];
 var ms_name = gm3.util.getMapSourceName(vis_path);
 var layer_name = gm3.util.getLayerName(vis_path);
 if(layer_name === 'all') {
  for(var j = 0, jj = map_sources[ms_name].layers.length; j < jj; j++) {
   var ms_layer = map_sources[ms_name].layers[j];
   var path = ms_name + '/' + ms_layer.name;
   if(ms_layer.name !== 'all' && path.indexOf(identify_layers) >= 0) {
    query_layers.push(path);
   }
 } else {
  query_layers.push(vis_path);
 }
}

Application.dispatchQuery(this.name, selection, fields, query_layers, this.template);
```

**Comment by theduckylittle** [comment]
So what's going on up there... 
1. It's getting a list of visible layers (the things you may wish to identify).
2. Getting a list of all layers which support identify.  
3. It's then going through all the visible layers and if one is named 'all', it iterates through the map source to find identifiable layers, else, it just checks that specific layer path to see if it's identifiable.

**Comment by mjreynolds** [comment]
This looks great. One template for all?

**Comment by theduckylittle** [comment]
Each `<layer>` would need to have its own until identify template.

**Comment by mjreynolds** [comment]
Will give that a shot. Thanks!
