### ISSUE TITLE
GeoJSON WFS support

### ISSUE THREAD

**Issue by nunziotocci** [geomoose/gm3#194]
Because GML 2.1.2 is roughly twice as large as GeoJSON, I'd like for GeoMoose to support it.
I was reading some of the source and it looks like you are already using GeoJSON to represent features internally, and the reason for using GML was because MapServer doesn't support GeoJSON.

**Comment by klassenjs** [comment]
GML is default for WFS in GeoMoose because GML is the standard format for WFS and thus what the most servers support.

I believe GeoMoose can take in GeoJSON as is (possibly outside the context of WFS at the moment.)  It wouldn't likely be hard to add support for GeoJSON via WFS (but might not be necessary.)

Both GeoJSON and GML benefit a lot from HTTP GZIP compression (although that is entirely between the web server and browser not the WFS server and GeoMoose)

MapServer certainly can produce GeoJSON responses to WFS requests and I have used that capabilities in other apps.

**Comment by nunziotocci** [comment]
@klassenjs Thanks for responding so quickly!

I am not using MapServer at this time (I am using a small, custom WFS CGI app), but I was under the impression it only returned GML because of [this comment](https://github.com/geomoose/gm3/blob/f0605df82f8469b9f9e81dfe50d7f73513a13396/src/gm3/components/map.jsx#L337) (see also [this comment](https://github.com/geomoose/gm3/blob/f0605df82f8469b9f9e81dfe50d7f73513a13396/src/gm3/components/map.jsx#L186))

I am returning GeoJSON at this time and GeoMoose doesn't seem to be doing anything with the data.

**Comment by tchaddad** [comment]
You can most certainly get geojson from a Mapservet WFS request if the
server is configured for it [1]. What Geomoose does with it though, I do
not know...

[1] http://mapserver.org/output/template_output.html

**Comment by theduckylittle** [comment]
I got motivated:
- https://github.com/geomoose/gm3/pull/196

**Comment by theduckylittle** [comment]
FWIW, I've added the OGR-based GeoJSON driver to the gm3-demo-data repository. This will allow for MapServer to output GeoJSON for WFS Feature queries.

**Comment by nunziotocci** [comment]
@theduckylittle Thanks! I am getting a different project ready for a release, but I'll get back to you as soon as I can.

**Comment by klassenjs** [comment]
I know I am late to the party, but just for completeness for those who
find this thread later... there is an easier way using MapServer's OGR
outputformats [1] that doesn't involve defining a template for each layer.

OUTPUTFORMAT
    NAME "geojson"
    DRIVER "OGR/GEOJSON"
    MIMETYPE "application/json" #; subtype=geojson; charset=utf-8"
    FORMATOPTION "STORAGE=stream"
    FORMATOPTION "FORM=SIMPLE"
    FORMATOPTION "LCO:COORDINATE_PRECISION=5"
END

[1] http://mapserver.org/output/ogr_output.html

**Comment by theduckylittle** [comment]
And for those playing the home game, the method @klassenjs  is what's now in the gm3-demo-data.

**Comment by theduckylittle** [comment]
Merged.
