### ISSUE TITLE
How-to Doc on adding Select is not rendering correctly

### ISSUE THREAD

**Issue by tchaddad** [geomoose/gm3#210]
This page leaves out the good bits:

http://geomoose.github.io/gm3/howto/add-select.html

**Comment by klassenjs** [comment]
I merged it, but didn't see the gh.io page update.  Assuming github is caching rather than it is still broken.

**Comment by theduckylittle** [comment]
@klassenjs , I'm seeing this fix this morning, closing this ticket.
