### ISSUE TITLE
Demo Backgrounds do not respect multiple="false"

### ISSUE THREAD

**Issue by tchaddad** [geomoose/gm3#211]
The demo backgrounds have `multiple="false"` at the group level, and yet they are rendered in the catalog with check-boxes rather than radio buttons, and can have multiple on at the same time.

**Comment by theduckylittle** [comment]
https://github.com/geomoose/gm3/pull/212

I know this will a slightly unsatisfying answer but we dropped support for the radio buttons in an attempt really clean up the catalog code.  The radio buttons and how they behaved were actually a bit of a state-management nightmare.

**Comment by tchaddad** [comment]
Fair enough - fixing the mapbook to reflect the change clears up the confusion. Thanks!
