### ISSUE TITLE
"Upload features" locks up layer with "bad" data.

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#215]
Continued from PR #205 

After uploading the parcels as GeoJSON but forgetting to transform them to 4326 first. It uploads, says success with 4040 features, but doesn't show them on the map. Trying again with the GeoJSON in 4326 again shows success with 4040 features but nothing added to the map.  Adding features with the drawing tools also fails.  Any existing features on the layer also become inaccessible.

Clearing all features (trash can icon) restores the layer.  Then drawing features or loading the correct (4326) GeoJSON works.  I would suggest this error be flagged or ideally invalid features not be loaded as right now to the casual user it appears that uploading a technically malformed, but likely common in practice GeoJSON file breaks GeoMoose.

Note: supporting other projections in GeoJSON was brought up in the PR and would be a nice enhancement, but this issue is about GeoMoose getting into a bad state.

Offending file created with:
```ogr2ogr -f GeoJSON parcels-utm.geojson . parcels```

Working file created with:
```ogr2ogr -f GeoJSON parcels.geojson . -t_srs EPSG:4326 parcels```

**Comment by theduckylittle** [comment]
The first file creates "NaN" numbers in the feature.

![image](https://user-images.githubusercontent.com/1282291/30089186-d5df1936-9270-11e7-96f6-a90192883b24.png)

This is causing the rendering to fail.  Technically, the *upload* is working.  It's that the source data is assumed to be EPSG:4326 and therefore the UTM data is, in fact, "bad" data.

This is just an observation, I'm working on a more proper fix now that I can see what's wrong.

**Comment by klassenjs** [comment]
Good job finding it.

So the upload works, but the layer render fails.  That makes sense given any other (existing or new) valid features no longer appear.

I presume the NaN is generated in proj4js while trying to go from 4326 to 3857 then OL chokes on the NaN.

**Comment by theduckylittle** [comment]
Correct, the NaN makes OL rendering impossible. It just pukes.  In all fairness, hardening OpenLayers may be a good idea but PR #219 at least makes sure the garbage is *mostly* renderable.
