### ISSUE TITLE
Windows KML Uploads

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/gm3#235]
Uploading the following KML works fine on Linux with Firefox and Chrome but fails on Windows with IE and Chrome.

[geomoose_1507742656590.kml.gz](https://github.com/geomoose/gm3/files/1376603/geomoose_1507742656590.kml.gz)

**Comment by klassenjs** [comment]
That's a good trick.

**Comment by klassenjs** [comment]
Not the core problem, but the KML file is missing a valid XML header.  `<?xml version="1.0"?>`

**Comment by klassenjs** [comment]
Looks like it might be all KML files on Windows (tested W7 w/FF,Cr,IE).  A OGR produced one fails too.  File extension doesn't matter (tried txt and xml).

**Comment by klassenjs** [comment]
My current thinking is it has to do with `if(file.type.indexOf('kml') ` failing to trigger on kml.

**Comment by klassenjs** [comment]
file.type is `""` on Windows and `"application/vnd.google-earth.kml+xml"` on Linux.

**Comment by klassenjs** [comment]
Not sure if should just detect with file.name.endsWith('.kml') or should sniff the contents. 
Try as JSON and if parsing fails, try again as KML?
Look for `{` or `<kml` or `<?xml` at the start of the file?
