### ISSUE TITLE
Lat/Lon reversed in coordinate display

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#239]
Coordinate order doesn't match the label order.

![screenshot from 2017-10-11 14-04-33](https://user-images.githubusercontent.com/165622/31460835-341fcc4c-ae8d-11e7-9562-60e5de729fbe.png)

**Comment by tchaddad** [comment]
I like this one!

**Comment by theduckylittle** [comment]
Any one have a preference? Fix the coordinate order or the label? Label fix is stupid easy, Coordinate fix may require more work.

**Comment by klassenjs** [comment]
Slight preference to lat, lon as that is more typical, but I am fine with self consistent.

**Comment by theduckylittle** [comment]
@tchaddad @elil  - Y'all are more geographers than we are ... what y'all want?

**Comment by elil** [comment]
Lat, Lon is more common and the order I'd go for.  I just realized that we use "Lon" but say "Long."

**Comment by klassenjs** [comment]
I say Lon.  Maybe MN vs OR?

**Comment by theduckylittle** [comment]
Merged. And closing...
