### ISSUE TITLE
Grid Shows Too Often

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/gm3#252]
The grid is tied to the data for a particularly layer but should be tied to a layer and a service. For example if `vector-parcels/parcels` was queried with identify, a single row in the table would be shown when really the grid should only display when used with select.

**Comment by tchaddad** [comment]
I think we can close this with the upcoming release

**Comment by chughes-lincoln** [comment]
Anecdotally related to this, I've configured the grid to show after queries. as this gives users a lot more functionality (being able to export your search results to a csv is huge, sorting and filtering is also nice). If changes are made, I wouldn't want the ability to configure the search in this way to be removed. (My identify also doesn't return grid results)

See: https://github.com/geomoose/gm3/issues/369

**Comment by theduckylittle** [comment]
Willing to close this unless @klassenjs  has more thoughts?

**Comment by klassenjs** [comment]
Nope.
