### ISSUE TITLE
More complex search example

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/gm3#259]
Gm 2.X had the ability to combine various fields into queries, GM3 only shows a very basic search as an example.

**Comment by elil** [comment]
Complex searches on a known data structure can be useful (when you know the data structure).  Another perspective on this could be to change how search works.  Perhaps one box that searches across multiple fields (or even multiple datasets) and returns results in a ranked way (or grouped by dataset and/or field way).

**Comment by theduckylittle** [comment]
There's always more room for an increasingly complex query engine. Some of which was definitely indulged in the previous versions of GeoMoose. PR #262 actually covers most of the ground that was being discussed in the room I was in.

**Comment by elil** [comment]
cool!
