### ISSUE TITLE
??? is returned with identify tool/html

### ISSUE THREAD

**Issue by butz1ben** [geomoose/gm3#278]
In the Results tab, character varying and numeric fields from Postgres with null values are returned with "???" when using the identify tool.  I've tried case statements in my SQL changing null values to have a space and then use nbsp; in my html without that making a difference.  Any idea as to why this could be happening or other alternatives to try?

**Comment by theduckylittle** [comment]
Can you post a sample JSON return as to what you're getting now? And possibly a SQL snippet?

**Comment by theduckylittle** [comment]
Aging this ticket out. For more help please post to the users list.
