### ISSUE TITLE
Identify template for multiple layers

### ISSUE THREAD

**Issue by cassiel74** [geomoose/gm3#284]
I have a map-source with 11 layers and I want the same template to be applied to all of them.
So, how can I avoid to copy/paste the same html snippet for 11 times in the same map-source?
I tried with general entities but can't get it to work

Regards

**Comment by klassenjs** [comment]
My strategy is to generate the mapbook either as a preprocessing step or on-the-fly (e.g. assembled from a database call) when my mapbooks start getting complicated/repetitive.

**Comment by cassiel74** [comment]
Great, also useful to serve mapbooks according to user privs.

**Comment by tchaddad** [comment]
I think this one can be closed?

**Comment by cassiel74** [comment]
Yep
