### ISSUE TITLE
Extra Attribution Button

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#297]
Somewhere between OL 4.4 and 4.6 an extra attribution button appeared in the lower-right corner of the map.

![image](https://user-images.githubusercontent.com/165622/38271941-6e96479a-374d-11e8-8c1c-009c5884054f.png)

**Comment by theduckylittle** [comment]
PR Available:
- https://github.com/geomoose/gm3/pull/300

**Comment by theduckylittle** [comment]
Fixed!
