### ISSUE TITLE
Cities and Villages Layer Fails

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#299]
XML Parsing Error: not well formed .../places.geojson
TypeError: i is not a function

**Comment by klassenjs** [comment]
Vector Parcels too but only with "i is not a function"

**Comment by klassenjs** [comment]
Expensive Parcels too.

**Comment by theduckylittle** [comment]
I'm not seeing this locally.

**Comment by theduckylittle** [comment]
Fixed with rebuild on server!
