### ISSUE TITLE
Coordinate Precision

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#304]
This started out as just a Lat/Lon issue, but looks like it may apply more broadly.  

Lat/Lon: The current three decimal places is only good to somewhat over 100m (at 45°N).  There may or may not be reasonably room for more digits in cursor tracking area, but we should probably show more digits in measure point.  Ideal would be to show the number of digits appropriate to the current zoom level and latitude.

**Comment by klassenjs** [comment]
(Similar scaling number of digits for X,Y might be good too).

**Comment by klassenjs** [comment]
Also applies to all forms of the measure tool.

**Comment by tchaddad** [comment]
I think this item is closable, BUT I've received a request to show 6 decimals in the lat / lon footer, if that is not too difficult of an amendment to add here...

**Comment by klassenjs** [comment]
It's not closable yet.  Only USNG got fixed.  Lat/Lon and X/Y should also be fixed to show an appropriate # of digits based on zoom level.

**Comment by tchaddad** [comment]
I'd like to prompt on this ticket in case it is doable in the next release. Just got a request about it today....

Specifically the issue of displaying 6 decimal places in the lat / lon footer.

If I should break that out into a separate ticket I can do that.

**Comment by klassenjs** [comment]
This ticket is more about displaying the "right" amount of precision based on zoom level.  

If you want 6 decimal places (always), I think that can already be done in app.js (for latlon and xy types):

```
    var point_projections = [
        {
            label: 'X,Y',
            ref: 'xy',
            precision: 0
        },
        {
            label: 'USNG',
            ref: 'usng'
        },
        {
            label: 'Lat,Lon',
            ref: 'latlon',
            precision: 6
        }
    ];
```

**Comment by tchaddad** [comment]
Ah nice - thanks for pointing to that!
