### ISSUE TITLE
Add lines to Drawing and Markup

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#31]
Are issues on 3.0 helpful?

Drawing and Markup does points and polygons but not seemingly lines.

**Comment by theduckylittle** [comment]
The issues are helpful as they make what we are doing in the background a bit more public.  I'll look at addressing this as soon as I can.  Though PR's are always welcome. ;)

**Comment by theduckylittle** [comment]
Magic! https://github.com/geomoose/gm3/pull/56

**Comment by theduckylittle** [comment]
Done!

**Comment by elil** [comment]
Thanks!
