### ISSUE TITLE
Doc -Print Layout - Errata

### ISSUE THREAD

**Issue by cabesuon** [geomoose/gm3#311]
Hi,

I think "data" field of image type should be "image_data", that's the property name in the code.

Regards,
Manuel

**Comment by theduckylittle** [comment]
Can you specify the line of code you are referring to?

**Comment by cabesuon** [comment]
Sorry, I assumed that was an errata issue.

File -> printModal.jsx
Method (line 122) -> addImage(doc, def)

When the method invokes the function of jsPDF  "addimage" passes as parameter  "def.image_data"

Regards,
Manuel

**Comment by klassenjs** [comment]
Ok, Where are you seeing "def.data"?

**Comment by cabesuon** [comment]
The documentation states:
"...
* `image` - Add an image to the map.
  * `data` - The bytes defining the image.
  * `x`, `y` - Define the upper left corner of the image.
  * `width`, `height` - The width and height of the image in the map (optional).
..."

But the property pass as a parameter is "image_data".

So the documentation should say "image_data" or the property should be "data".

Regards,
Manuel

**Comment by theduckylittle** [comment]
Cool, got a PR that clarifies the docs. Thanks for the catch!

**Comment by cabesuon** [comment]
Great, thanks!.
