### ISSUE TITLE
Search - field required or no field complete

### ISSUE THREAD

**Issue by cabesuon** [geomoose/gm3#316]
I couldn't find any way to specified that a field is required for the search, is this supported or going to be supported anytime?.

Right now if a field is require and is not complete or if no field was complete I have to pass a false query to have 0 result. I a better way to do this, maybe the idea is to implement another search with more capabilities.

Regards,
Manuel

**Comment by theduckylittle** [comment]
Can you consider making this into a PR? That way others can use it more readily?

**Comment by cabesuon** [comment]
OK, I will do it on the weekend.

Regards
Manuel

**Comment by cabesuon** [comment]
I have been busy with other projects thats why It took me some time to get back on this, sorry about that.

I finally made the pull request https://github.com/geomoose/gm3/pull/340. It is different from what I posted here because the version we are managing is older, but I think it looks cleaner.

Regards
Manuel

**Comment by elil** [comment]
Should we add this to the docs?  Or leave the issue open and add a docs tag?

**Comment by theduckylittle** [comment]
No, if we have solved it functionally (but without docs) then we should
create a separate issue to make sure docs are handled. Zombie issues are
problematic for version and progress tracking.
