### ISSUE TITLE
Reference Scale Component

### ISSUE THREAD

**Issue by butz1ben** [geomoose/gm3#317]
Add a reference scale display component

**Comment by klassenjs** [comment]
I'm not sure I understand.  Have you tried one of the scalebar layers?

**Comment by butz1ben** [comment]
Sorry. I have been emailing with Dan about it. He said to put in a ticket to maybe have it included in the next release of GeoMoose 3.

I was very non-descriptive in my submittal as he knows what I’m requesting.

Thank you Jim,

Ben

**Comment by theduckylittle** [comment]
I think this will be covered in 3.5.0
