### ISSUE TITLE
Printing Enhancements

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#327]
1) Print to a specified scale
2) Print legends
3) Print compass rose
4) Print attribution (ex. for OpenStreetMaps)

**Comment by tchaddad** [comment]
+1 for adding back the printing of legends

**Comment by christian4423** [comment]
Maybe add crossOrigin default to Anonymous for printing. 

In OL in image.js the code 

```
  this.image_ = new Image();
  if (crossOrigin !== null) {
    this.image_.crossOrigin = crossOrigin;
  }
```

When printing I get a canvas tainted error. I could  not find in the gm3 code where you all call to ol/image.js to pass it the anon value. 

I changed the ol code to 

```
  this.image_ = new Image();
  if (crossOrigin !== null) {
    this.image_.crossOrigin = crossOrigin;
  }else{
    this.image_.crossOrigin = "Anonymous";
  }
```

for the meantime but it would be nice if gm3 did that out of the box.
