### ISSUE TITLE
Jump to External Maps

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#328]
GeoMoose 2.x had a tool to jump into external web maps (ex. Google Maps/Street View, Bing Maps/Obliques, Speckly, ...) at approx the same location and scale as the GeoMoose map.

**Comment by tchaddad** [comment]
+1 for this one, the Streetview link format from 2.9 was:

`http://maps.google.com/maps?hl=en&ie=UTF8&spn=0.115896,0.239639&z=12&layer=c&cbll=[LAT],[LONG]&cbp=12,0,,0,-4.1&view=map&ll=[LAT],[LONG]`
