### ISSUE TITLE
Add padding around catalog/tabs

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#329]
The "folders" are right up against the edge and sometimes look odd.

Looks like this needs to be applied to the div inside of the tab-container div otherwise the tab content gets shifted off the other edge instead of line-wrapped at the appropriate point.  1-2px seems enough.

**Comment by chughes-lincoln** [comment]
I added this code to my site.css to overwrite the geomoose.css, which worked:

```
.catalog.searchable {
  padding-top: 40px;
  padding-left: 4px;
}

.service-manager {
  padding-left: 4px;
}

.catalog.favorites.flat {
  padding-left: 4px;
}

.catalog.visble-layers.flat {
  padding-left: 4px;
}
```

Also, the div for the visible layers is misspelled - "visble"
