### ISSUE TITLE
Find me/Track me enhancement

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#333]
I've been playing with using GM3 (desktop example) on my phone and it would be nice if Find Me would drop a point (probably on it's own layer) that could then be used both as a reference on the map and as a source for queries (e.g. select features).

It would also be nice if there was a track me that did the same, but automatically updated as you move.

**Comment by chughes-lincoln** [comment]
Not sure if this is known, but I've noticed that the GM3.3.1-beta does drop a point after using it, although apparently only after you do an unrelated search or selection.

That may give a hint to how to get it to drop a point when you want it to.
