### ISSUE TITLE
Measure bearing logic

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#34]
The Measure logic for bearing  [here](https://github.com/geomoose/gm3/blob/56243b399d57b0b1237cc398a94172343d943a3e/src/gm3/components/measure.jsx#L60-L71), incorrectly returns North and East for South and West.

**Comment by klassenjs** [comment]
I think it looks consistent anyway to me.  If A is (0,0):

B = (0,1) then A > B is false so North
B = (1,0) then  A > B is false so East
B = (1,1) then rise > 0 and run > 0 so NE

So the question is (for the doxygen comment): What are point A and B
supposed to be?  From and To or To and From.

However the [0] vs. .x inconsistencies are kind of frightening.

**Comment by elil** [comment]
the .[0] vs .x but also the .y.  The if currently doesn't returns true which then goes to else and returns for both cases.

**Comment by theduckylittle** [comment]
Someone should really write a test for that ... and fix the logic there.  Nothing like partially ported code...

**Comment by theduckylittle** [comment]
Merged the PR.

**Comment by elil** [comment]
What is the source and how is the [3.0 demo](http://demo.geomoose.org/3.0/demo/) updated?  I'm trying to determine if I can test this in the demo and close the ticket.

**Comment by theduckylittle** [comment]
Demo should be updated automatically but we changed some file structures. Maybe @klassenjs can check on that?

**Comment by klassenjs** [comment]
The demo updates are FUBARed right now.  After the Tuesday changes I need
to rethink how it is built.  Probably will happen Monday.
