### ISSUE TITLE
Unicode characters when typing title while using print service 

### ISSUE THREAD

**Issue by stathisar** [geomoose/gm3#348]
When typing the title name of the map while using the print service, if the characters are Greek or Cyrillic they are not displayed in the pdf. It seems that there is a lack of support of Unicode characters

**Comment by klassenjs** [comment]
Confirmed.
Looks like codepoints less than work (such as `é` U+00E9).

`ͻ` (U+037B) gets rendered as `{`
`؆` (U+0606) doesn't get rendered at all.

**Comment by klassenjs** [comment]
Looks like support was added in jsPDF 1.4+ and also requires an appropriate font (I'm not sure if whatever font we are using counts for that or not).

More info in: https://github.com/MrRio/jsPDF/issues/12

**Comment by theduckylittle** [comment]
In a local branch, I've upgraded jsPDF to 1.5.x but that didn't fix the problem as there does need to be more work around font support.  I'll need to keep this issue open as I suspect it may lead to needing to do some documentation on how to properly add a new font to the PDF code.
