### ISSUE TITLE
Zoom to Selected Item can go too far

### ISSUE THREAD

**Issue by tchaddad** [geomoose/gm3#349]
Zooming to selected lines or Polygons works well. However for for points, when a user clicks to zoom to a particular location, you often get zoomed to a level  level that is super close (e.g. past the zoom level of any available base maps).

It would be nice if the "zoom to" had an optional setting for max zoom level (e.g. Zoom level 18), so that in addition to zooming to the x, y, the service would respect the specified z.

**Comment by theduckylittle** [comment]
Is this the same?

* https://github.com/geomoose/gm3/pull/355

**Comment by tchaddad** [comment]
Yes sounds like it....I'll test your fix.

**Comment by theduckylittle** [comment]
Let's track any follow up work in #360
