### ISSUE TITLE
Select pipelines gives an error

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#357]
1. Catalog --> turn on pipelines
2. Select features --> Draw polygon --> [draw generous polygon] --> Query Layer --> Pipelines --> Go
3. No valid selection geometry.

**Comment by theduckylittle** [comment]
Doh! This was a simple one. The Pipelines shouldn't be there. The layers-list drop down was not honouring the "require select template" filter.

**Comment by elil** [comment]
Looks good in the demo now.

**Comment by elil** [comment]
It looks like my review and closing based on the demo was mistaken.  I failed to make the pipelines visible before testing, that is why they were not present in the Query Layer.  (If only I had followed my own detailed steps above!)

Reopening to let someone else test properly.

**Comment by klassenjs** [comment]
Try it now.  I think you got ahead of the buildbot.

**Comment by elil** [comment]
Thanks, looks good now!  Now, I'm closing...
