### ISSUE TITLE
Manipulate selection sets

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#358]
When a selection set is made, it can't be modified.  It would be helpful to be able to modify a selection set.  

In past versions, this was limited to removing features from the selection set.  

This issue could be changed to a larger topic of managing selection sets to include other tangential topics.

**Comment by theduckylittle** [comment]
Does this refer to, say, from the grid being able to drop a particular feature from the map/grid? Like a remove from results button or something?

**Comment by elil** [comment]
Yes, exactly.

**Comment by chughes-lincoln** [comment]
There's the ability of achieving this functionality partially by using the filter option within the grid from a selection (clicking the filter icon next to the column name). As long as the field you're filtering is unique (like a PIN or parcelid) that would allow you to remove individual results. Not as convenient as clicking remove result, but gets you part of the way there.

**Comment by chughes-lincoln** [comment]
Is there anything desired here that wasn't achieved with the remove results button?

**Comment by theduckylittle** [comment]
I believe we have satisfied the spirit of the issue.

**Comment by elil** [comment]
Sounds good!
