### ISSUE TITLE
Make select automatically select the feature from results.

### ISSUE THREAD

**Issue by christian4423** [geomoose/gm3#363]
Is there a way to make the select service select the feature from results when drawing from a point?

Right now, a user will have to 
1. Draw a point
2. Hit GO 
3. Select the feature from results
4. input the buffer
5. hit GO. 

Desired use case is: 
1. Draw point
2. input the buffer
3. select GO. 

I was able to turn AutoGO on but when I apply a buffer, it runs it at 0 and it makes a selection automatically... So I left it on. 

I made the select run on click without selecting GO with this line of code in serviceManager.jsx
```
if(service_def && (service_def.autoGo || nextProps.map.interactionType === "Point")) 
```
```
            if(service_def && (service_def.autoGo || nextProps.map.interactionType === "Point")) {
                let selection = nextProps.store.getState().map.selectionFeatures;
                if(selection.length > 0) {
                    // okay, there *is* a selection feature.
                    let fid = selection[0].properties.id;
                    if(nextState.lastFeature !== fid) {
                        this.setState({lastFeature: fid});
                        this.startQuery(service_name);
                    }
                }
            } 
```

![image](https://user-images.githubusercontent.com/6324867/52669469-259d5580-2ee4-11e9-9b27-c3115c0aac5b.png)

**Comment by klassenjs** [comment]
I can see why you would want this for specific cases, but I don't think the select.js service designed to do that (instead being designed to allow users more flexibility by letting them pick how to chain queries).

I'd probably do this by creating a new service starting from select.js and modifying it to chain the two queries for your specific case, but others may have better ideas.

**Comment by christian4423** [comment]
Thank you for some direction on going forward. I will continue with your suggestion. Want me to close this or post my result?
