### ISSUE TITLE
Buffers seem too small

### ISSUE THREAD

**Issue by tchaddad** [geomoose/gm3#366]
Following up from the discussion in https://github.com/geomoose/gm3/issues/361, buffer distances seem too small by 25-30%, which seems to be the same error around scalebars.

leaving this as a stub, and will come back and attach screenshots in the next few days.

**Comment by tchaddad** [comment]
Here's an example:

- Browse the demo for some adjacent parcels that look the same width
- measure to get approximate widths to confirm (in this case it was ~1300 feet)
- set the buffer distance to 1300 feet and choose to select with a point
- click in a corner between two of these similarly sized polygons
- buffer draws, and clearly is too short to reach the expected distance of ~1300 to the edge of the neighboring polygon
- distance seems off by about the same % as mentioned in the scalebar issue (https://github.com/geomoose/gm3/issues/361)

Like so:

![image](https://user-images.githubusercontent.com/1042618/53620583-58b03c00-3ba8-11e9-9d22-ecaef68267a6.png)

**Comment by theduckylittle** [comment]
The aggravating part is that the measurement tools and the buffers are likely _more accurate_ than what is being rendered on the map.  This is pretty high on my 'to investigate' list but I just haven't had an open window of opportunity yet.

**Comment by chughes-lincoln** [comment]
Looks like this is fixed in the current demo
