### ISSUE TITLE
Display grid results after query

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#369]
Is there the ability to easily display the grid results when doing a search? 

I was able to return grid information for a search by doing any selection (which creates a table), and then doing a search (which updated the table with the query information), but I wasn't able to simply search and return a grid without doing an unrelated selection first.

The grid provides additional functionality (sorting, filtering, saving results as a csv) that would be useful to be able to do with searches.

**Comment by klassenjs** [comment]
Cool, I didn't know it worked with searches at all.  It was primarily
designed to work with the select tool.

I could see that being useful though.

**Comment by chughes-lincoln** [comment]
I made some minor modifications to the search.js file in the services folder and got the grid to display for searches just like it does if you have it configured to display for selections. Main caveat is that this references the same grid templates as the selection, so it forces you to use a grid for both select and search or for neither, rather than one or the other.

See changes:

https://github.com/geomoose/gm3/blob/master/src/services/search.js#L40 

Added this line of code from select.js after line 40 of the original

`    this.showGrid = options.showGrid !== undefined ? options.showGrid : true;`

Added this section from select.js before Application.dispatchQuery (Line 107)


        
            var templates = [this.template];
            if(this.showGrid) {
                templates.push('@gridColumns');
                templates.push('@gridRow');
            }

And then changed this.template to templates in the Application.dispatchQuery section below

      Application.dispatchQuery(
            this.name,
            selection,
            this.prepareFields(fields),
            this.getSearchLayers(this.searchLayers, fields),
            templates
        );

**Comment by chughes-lincoln** [comment]
Is there any desire to add my changes to show the grid in search results in the demo? Currently search results only return tab results, which limits you a bit in what you can do with them (mainly being able to export results to a csv)

**Comment by brentfraser** [comment]
Yes.  I think this would be a great addition

**Comment by chughes-lincoln** [comment]
I also think this pairs well with the ability to have the grid be minimized by default. Therefore you get your normal tab results, and have the ability to see table results or export to csv if you want without cluttering your map.

**Comment by brentfraser** [comment]
@chughes-lincoln : another solution to "minimized by default" would be to tweak the results tab a bit:

1. Move the big zoom-to-results "button" to a smaller icon on the results tool bar (along with the clear-results icon) 
2. Add a show/hide-table icon to the toolbar for showing the results in the table.

**Comment by chughes-lincoln** [comment]
Thanks Brent, that looks like it could be an effective solution.

**Comment by brentfraser** [comment]
To move the zoom-to-results tool into the tool bar:
```
diff --git a/src/gm3/components/serviceManager.js b/src/gm3/components/serviceManager.js
index 6b7eaf8..bae20b8 100644
--- a/src/gm3/components/serviceManager.js
+++ b/src/gm3/components/serviceManager.js
@@ -150,13 +150,6 @@ class ServiceManager extends React.Component {
                     <div className='label'>{this.props.t('layers')}</div>
                     <div className='value'>{ layer_count }</div>
                 </div>
-
-                <div className='results-info-item zoomto'>
-                    <div className='label'>{this.props.t('zoomto-results')}</div>
-                    <div className='value' onClick={() => { this.props.zoomToResults(query); }}>
-                        <span className='icon zoomto'></span>
-                    </div>
-                </div>
             </div>
         );

@@ -165,6 +158,13 @@ class ServiceManager extends React.Component {
                 <div className='results-header'>
                     { this.props.t(service_title) }
                     <div className='results-tools'>
+                        <i
+                            title={this.props.t('zoomto-results')}
+                            className='icon zoomto'
+                            onClick={() => {
+                                this.props.zoomToResults(query);
+                            }}>
+                        </i>
                         <i
                             title={this.props.t('results-clear')}
                             className='icon clear'
```
---
and 
```
diff --git a/src/less/results.less b/src/less/results.less
index 6d2cdcc..8596224 100644
--- a/src/less/results.less
+++ b/src/less/results.less
@@ -86,7 +86,7 @@
         display: flex;

         .results-info-item {
-            width: 30%;
+            width: 50%;

             padding: .25em;
             margin: 5px;

```

**Comment by brentfraser** [comment]
Result:
![image](https://user-images.githubusercontent.com/1638313/89654818-7813c400-d886-11ea-8f4d-4c8f26446911.png)

**Comment by brentfraser** [comment]
I've applied @chughes-lincoln changes to my local copy, and it works great!   

I'm not sure how (or if?) we should allow the configuration of results to be either/or for both Select and Search, like:

|Operation:| Tab: | Grid: |
|-----------|-----|-------|
|Select       |  <template name="select" | <template name="select-gridColumns", "gridRow" |
|Search|  <template name="search" | <template name="search-gridColumns", "gridRow" |

**Comment by theduckylittle** [comment]
There is a lot of run-on here with some ins-and-outs about various changes y'all made. If any of them are to be included then we need to break this up into separate requests.

PR #587 adds the ability to add grid to search and identify more flexibly. You can spec a different set of templates for the different services.

**Comment by chughes-lincoln** [comment]
PR https://github.com/geomoose/gm3/pull/587 addresses my main suggestion. Thanks!
