### ISSUE TITLE
App.addProjection appears to not work (Configure coordinate display)

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#370]
I've been unable to add a new projection for the coordinate display in the footer for the GeoMoose 3.3 demo.

See code from How-to configure coordinate display:

```
app.addProjection({
    ref: 'ESRI:102003',
    def: '+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs'
});

app.add(gm3.components.CoordinateDisplay, 'coordinate-display', {
    projections: [
        {
            label: 'Albers:',
            ref: 'ESRI:102003'
        },
        {
            label: 'USNG:',
            ref: 'usng'
        }
    ]
});
```

I've also been unable to simply substitute 

`            ref: 'xy'`

for

`ref: 'EPSG:26915'`

as in the Configure Coordinate Display section of the GeoMoose 3.2 workshop. However, when I substitute xy for a projection that's built in such as EPSG:4326 it correctly changes the coordinates.

**Comment by klassenjs** [comment]
This works for me on one of my sites:

```
    app.addProjection({
        ref: 'EPSG:200068',
        def: '+proj=lcc +lat_2=44.88333333333333 +lat_1=45.13333333333333 +lat_0=44.79111111111111 +lon_0=-93.38333333333334 +x_0=152400.3048 +y_0=30480.0610 +unit=sft +to_meter=0.30480060960122 +a=6378418.941 +b=6357033.310 +no_defs'
    });

    app.addProjection({
        ref: 'EPSG:26915',
        def: '+proj=utm +zone=15 +ellps=GRS80 +datum=NAD83 +units=m +no_defs'
    });
```

```

    var point_projections = [
        {
            label: 'X,Y',
            ref: 'EPSG:200068',
            precision: 0
        },
        {
            label: 'USNG',
            ref: 'usng'
        },
        {
            label: 'Lat,Lon',
            ref: 'latlon'
        }
    ];

    app.add(gm3.components.CoordinateDisplay, 'coordinate-display', {
        projections:  point_projections
    });
```

**Comment by chughes-lincoln** [comment]
That fails for me on GeoMoose 3.3.0 (with MS4W 4.0.0). What version are you running?

It doesn't appear to give me any obvious errors, any coordinates that reference added projections just don't show up in the footer.

**Comment by klassenjs** [comment]
Yep, it certainly looks broke in 3.3.

**Comment by klassenjs** [comment]
Testing with EPSG:26915, it looks like isDefinedProjection is returning false.

coordinate-display.js:109
```
                const isDefinedProjection = (proj.get(projection.ref) !== null);

```
proj.get('EPSG:26915') returns null
proj.get('EPSG:32615') works

So It looks like app.addProjection() in app.js isn't working.

**Comment by klassenjs** [comment]
I suspect that app.js:addProjection() may be operating on a different proj instance than the coordinate display.

**Comment by chughes-lincoln** [comment]
Thanks, good to hear it isn't just me.

**Comment by tchaddad** [comment]
So it’s just a matter of tracking down the other project file and adding
the missing definition.

**Comment by klassenjs** [comment]
It isn't so much a different file as two instances of the proj library in
GeoMoose (that is assuming I am right about what is going on, which I am
not 100% sure about).

**Comment by theduckylittle** [comment]
Relevant PRs:
 * https://github.com/klassenjs/gm3/pull/1
 * https://github.com/geomoose/gm3/pull/372

I think those merged together will fix the problem.

**Comment by theduckylittle** [comment]
OpenLayer's carries around it's own internalized version of Proj. But you can use an external version of proj which allows for much more flexibility. Sometimes ensuring the correct proj is being used in the correct place is more difficult with OL 5+. These PRs address it.
