### ISSUE TITLE
Print extent

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#374]
The print in the 3.3.1-beta on geomoose.org (and on my 3.3.0 setup) zooms in on the data frame when printing at the normal resolution (See example below). Increasing the resolution then zooms out rather than just changing the resolution at the same extent. Not sure if this is a bug but I thought I'd mention it.
![PrintClip](https://user-images.githubusercontent.com/43766648/56373134-2fc62380-61b5-11e9-99bf-35d26a9c7487.PNG)

**Comment by theduckylittle** [comment]
This was actually a design decision. We have the ability to preserve scale or attempt to adjust the extent. What we found is that the differences in print layouts made preserving extent a losing battle. There were also issues with the map "changing" when we tried to preserve extent -- most style elements are keyed on scale so sometimes entire layers would disappear from the map during printing.
