### ISSUE TITLE
Measure feature from result fails when parcel isn't contiguous

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#375]
Trying to measure the area of a feature from results fails when the polygon isn't contiguous (in my 3.3.0 setup or the 3.3.1-beta on geomoose.org).

i.e. search for or select parcels, click Measure, Feature from: Results, and click on a parcel that isn't contiguous (i.e. property owned by 'Mitchell Walters')

**Comment by theduckylittle** [comment]
This looks to be an internal OpenLayers bug with the getArea() function. We'll need to research either using turf's implmentation or the ol.sphere version of getArea. I'll leave this for 3.4 but don't want to make another tweak to the measure tools this close to release.

**Comment by chughes-lincoln** [comment]
Just to document this a bit more, it looks like it also fails when a feature has holes (i.e. it doesn't only fail when a feature is a multi-part polygon).

**Comment by chughes-lincoln** [comment]
Tested it out on my site, now works for multi-part features and features with holes.
