### ISSUE TITLE
Drop or update the "mobile" example

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#376]
The mobile example has not kept pace with the desktop example (partially because the desktop example while not optimized for mobile is functional on mobile).

The main issues I see:
* It isn't part of the automated tests
* Has fallen behind the desktop example
* Relies on an old JQuery version with multiple CVEs

I am torn between not wanting to ship a component in such a state and not wanting to default to the desktop example only (GeoMoose 3 was built to be able to support a lot more than the one demo app).

**Comment by tchaddad** [comment]
If you want a random anecdote from the field: 

Just a few weeks ago someone asked me about problems using 3.x desktop version on Android phones (apparently it's basically non-functional?). I couldn't confirm b/c I don't have one, and I've never really played with the mobile demo. 

Anyhow, they then went the mobile route and had a functional version of what they wanted up within 24 hours. Not everything was perfect but it was enough to make me believe that there is definitely value in keeping it.

**Comment by klassenjs** [comment]
It is good to know people find it useful.

In my testing the desktop version "works" on Chrome on my Android phone, but you have to be patient and careful with page zooming otherwise you get trapped over part of the map.  However, if you "fix" this by setting the page to not zoom on mobile (by adding the magic line in the desktop.html header), then everything is too big and there isn't enough screen real estate to be useful.  This is clearly not ideal and part of why the mobile example was created (the other part was to showcase that radically different layouts were possible with the same underlying code and data).

I haven't tested in awhile, but the desktop example should work acceptably well on a tablet.

It might be worthwhile adding a simple map example too (something that could be embedded in another page - drop most/all the controls and just leave the map).

**Comment by brentfraser** [comment]
Currently the desktop version renders the text and icons too small on a phone display.  To scale them up add:
`
<meta name="viewport" content="width=device-width, initial-scale=1">
`
in the head portion of desktop's index.html.
See #256 
But making them larger/readable does create a layout problem.

**Comment by theduckylittle** [comment]
Ref: https://github.com/geomoose/gm3/pull/412
