### ISSUE TITLE
Most tests fail

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#379]
### Versions:
* Geomoose: 3.3.1
* Host OS: Windows 7
* npm: v10.15.3
* jest:  jest@22.4.4

Following the instructions on the "Getting Started with GeoMoose 3 on Windows" (and then on the "*nix-systems") page, running
`node test`
results in 20 of 29 tests failing with 
`Failure message: EBADF: bad file descriptor, close`

After Googling, I was able to reduce the test failures to 1 when I inserted:
`   "resolutions": {
    "write-file-atomic": "2.4.1"
  },
`
in the GeoMoose package.json file (at the same level of "babel", "jest", etc).

Thoughts?

**Comment by klassenjs** [comment]
Assuming you have a clean git repo

```
rm -rf dist node_modules
npm install
npm test
```

Should work.  It will skip a couple of tests if require node modules (canvas and xmlshim) that are required only for running the tests (map and WFS) aren't available.  This was done because those modules are hard to compile on Windows.  

Note: `grunt build` is independent from the tests.  It can be run before the tests, but it doesn't have to be run before the tests.

The above works for me with:
* Win 7
* Node v10.15.1
* Geomoose master (3e839a2)

**Comment by klassenjs** [comment]
I am seeing a lot of test failures when running from the GeoMoose 3.3.1-beta MS4W package.

**Comment by brentfraser** [comment]
After deleting my gm3 folder, then doing:
```
cd c:\GeoMoose
git clone https://github.com/geomoose/gm3.git
npm install
npm test
```
the tests run successfully (and skipped two as you mentioned):
```
 PASS  tests\gm3\components\catalog\tools\legend.test.js (5.111s)
 PASS  tests\gm3\components\catalog\tools\refresh.test.js (5.171s)
 PASS  tests\gm3\components\catalog\tools\metadata.test.js
 PASS  tests\gm3\components\catalog\tools\upload.test.js (6.414s)
 PASS  tests\gm3\components\measure.test.js
 PASS  tests\gm3\components\catalog\tools\clear.test.js
 PASS  tests\app.test.js
 PASS  tests\gm3\components\layers\wfs.test.js
  ? Console

    console.error tests\gm3\components\layers\wfs.test.js:43
      Skipping WFS tests without xmlshim installed.

 PASS  tests\gm3\components\toolbar.test.js (7.279s)
 PASS  tests\gm3\components\coordinates.test.js
 PASS  tests\gm3\components\catalog\tools\download.test.js
 PASS  tests\gm3\components\catalog\tools\zoomto.test.js
 PASS  tests\gm3\jsts.test.js (7.672s)
 PASS  tests\gm3\components\drawTool.test.js
 PASS  tests\gm3\components\catalog\tools\draw.test.js
 PASS  tests\gm3\components\catalog\tools\fade.test.js
 PASS  tests\gm3\components\catalog\tools\up.test.js
 PASS  tests\gm3\application.test.js
 PASS  tests\gm3\util.test.js
 PASS  tests\gm3\reducers\ui.test.js
 PASS  tests\gm3\components\modal.test.js
 PASS  tests\gm3\reducers\mapSource.test.js
 PASS  tests\gm3\actions\toolbar.test.js
 PASS  tests\gm3\reducers\map.test.js
 PASS  tests\gm3\reducers\toolbar.test.js
 PASS  tests\gm3\components\layers\wms.test.js
 PASS  tests\gm3\components\catalog.test.js (13.226s)
 PASS  tests\gm3\components\map.test.js (14.588s)
  ? Console

    console.error tests\gm3\components\map.test.js:60
      Skipping map tests without node-canvas installed.


Test Suites: 1 skipped, 28 passed, 28 of 29 total
Tests:       1 skipped, 91 passed, 92 total
Snapshots:   0 total
Time:        17.269s
Ran all test suites.
```

**Comment by klassenjs** [comment]
Cool.

It looks like package-lock.json isn't getting added to the zipfiles.

**Comment by brentfraser** [comment]
Um, where are you getting the  GeoMoose 3.3.1-beta MS4W package from?

**Comment by klassenjs** [comment]
https://www.geomoose.org/download.html

Where are you getting GeoMoose 3.3.1 from (as it hasn't been released yet)?

**Comment by klassenjs** [comment]
Looks like we need to add a `npm shrinkwrap` step to the build.

**Comment by klassenjs** [comment]
At the moment I'm not sure if the npm-shrinkwrap.json file is supposed to replace package-lock.json or supplement it.

https://docs.npmjs.com/files/shrinkwrap.json

**Comment by klassenjs** [comment]
Alternatively... we could require building from git rather than the NPM/ZIP packages.

**Comment by brentfraser** [comment]
Whichever works.  My goal is create a detailed "how-to" on debugging (including stepping through the JavaScript via a browser's dev tools) GeoMoose on Windows.

**Comment by klassenjs** [comment]
A worthy goal that is.

Using `debug.html` and `grunt serve` are the important parts (which I think you have figured out already).  Firefox and Chrome should work for debugging on the browser side.  I haven't tested IE/Edge.

**Comment by brentfraser** [comment]
Documentation has been updated (thanks @klassenjs !)
