### ISSUE TITLE
Select by anything other than point broken

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#393]
GeoMoose Demo:
Turn on parcels
Click "Select Features"
Click "draw polygon"
Draw polygon covering several parcels
Click Go

No results are returned.

**Comment by theduckylittle** [comment]
I think this is related to #373

**Comment by brentfraser** [comment]
Yes, I tried to fix the split-on-undefined problem by using a typeof test instead of ===, and while it worked, there were other problems leading me to believe it is a symptom not the root problem.  Best left to the pros (@theduckylittle ,etc)

**Comment by theduckylittle** [comment]
Think we got this one into 3.3.1 :) Thanks everyone.
