### ISSUE TITLE
Add scaleline to printing

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/gm3#398]
As we dropped the mapserver raster scalebars, we should add a version of the OpenLayers-style scale line to the print outs.

**Comment by tchaddad** [comment]
Any chance of this one making it into 3.5?

**Comment by theduckylittle** [comment]
@tchaddad - Looking to try and get this in. I have a PR that @klassenjs and I have differing perspectives on 'working.' We may need more testing and feedback.

**Comment by tchaddad** [comment]
Sure thing.

Saw both your tests and noted that @theduckylittle tested miles, while @klassenjs tested kilometers. 

Could there be a units conversion problem somewhere that is affecting the results of @klassenjs 's test?

**Comment by tchaddad** [comment]
Works for me now, for all print options

**Comment by tchaddad** [comment]
Closing.
