### ISSUE TITLE
Select by Box

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#408]
It would be really useful to add the ability to select features using a box (or to get feedback about how this could potentially be added). 

The main issue for me with GeoMoose 3 is that it isn't quite as user-friendly as GeoMoose 2. If our users have to click 4 times to create a polygon rather than just clicking and unclicking to create a box, they may just not use it rather than sucking it up and putting in the extra effort.

**Comment by theduckylittle** [comment]
@chughes-lincoln  - After this is merged, I would greatly appreciate a follow up PR with some docs.

@klassenjs - Are we missing a 3.5? This may be a 3.5 thing... though I've sometimes considered "forward ports" to be "bug fixes" as from the user perspective they are "Broken" from 2.x

**Comment by klassenjs** [comment]
I'm fine calling it 3.5. 

Personally, I'd expect minor bumps to be the most common.  It just means we added something and did our best not to break anything.  

We technically could release a 3.4.1 with the fixes only, but all that would be is 3.5 w/o Box support, which isn't something expect would be worth the effort.

**Comment by tchaddad** [comment]
Works well - I think this will be a popular one...
