### ISSUE TITLE
Select doesn't retain default option

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#428]
This isn't a huge issue but I know it will trip some people up. On the demo if you do a selection and then click Select Features to do another selection, your default 'Using' option is no longer selected. 
It is selected if you click a different tool (i.e. identify/search) before trying to do another selection

**Comment by theduckylittle** [comment]
I think #431 will fix this bug.

**Comment by chughes-lincoln** [comment]
Works well now.
