### ISSUE TITLE
Select - autogo only allows selection of default selection layer

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#441]
If you've set autogo to true, it only allows you select the default layer. i.e. if you switch the drop-down from your default layer 'Parcels' to something else, it still selects Parcels.

**Comment by theduckylittle** [comment]
@chughes-lincoln - I think this was similar to another reported bug that should be fixed in 3.6.0? Can you confirm?

**Comment by chughes-lincoln** [comment]
There are a few issues related to the default selection options and one related to autoGo. 

In terms of autoGo, if you set it to only use options that are more compatible with autoGo (i.e. Don't use Modify/MultiPoint/Select Feature on Map), it reruns the previous geometry anytime you click on the select tool in the toolbar. I understand that autoGo is meant for identify and its ilk, but it would be nice to be able to set it for specific select tools that only use select by box/point.

There's also an issue where if the user doesn't click 'End Drawing' before choosing another tool it retains the default option from the first tool. See https://github.com/geomoose/gm3/issues/454. I don't know if this is necessarily a bug, as you're supposed to click 'End Drawing' when you're done with a tool, but it's reasonable to expect that some users won't, and will get confused by the default option being changed.

I also haven't been able to set the default selection option when using a drawer. See https://github.com/geomoose/gm3/issues/463. (The default option isn't retained when choosing any tool in a drawer).

**Comment by theduckylittle** [comment]
I think #528 addresses all of the above issues individually. When you do switch from the default layer it resets when the form is started over but other than that I think the other state issues may be figured out.

**Comment by chughes-lincoln** [comment]
It's working smoothly without autoGo, thanks for those adjustments!

I'm noticing a couple issues. If I have my select tool configured to use a drop down list it's still only allowing me to only select the default layer. Other than removing the options definitely incompatible with autoGo my select configuration should be the same as the demo. If I don't have keepAlive set to true, there's also still the issue of the tool rerunning the previous selection when you click on the tool in the toolbar.

There are also issues when buffering directly from the results tab. If you buffer from results it appears to only allow you to select the dataset that you buffered for going forward. I can't determine if that's the case if you have a select tool with a drop-down list, but I noticed it when you have specific select tools set up to interact with individual datasets. This is the case even if you clear your results, clear your selection geometry, and end the tool by clicking the button in the top-right. It's not the case if you don't have autoGo configured.

**Comment by theduckylittle** [comment]
I'm going to close this issue but if you can document more distinct steps then I can try to recreate and fix for the desired behaviour.
