### ISSUE TITLE
Select Feature from results - odd behavior

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#448]
I added this as a comment but it's probably best to separate it into its own issue as it probably has a different solution. See https://github.com/geomoose/gm3/issues/365

If you do a selection and then return to the select tool to buffer your previous selection, choosing Feature from Results, and buffer without clicking on the map, it runs the selection again with the initial selection geometry, rather than recognizing that you're trying to buffer your results. Ideally, when you have Feature from: Results selected, it should recognize that you need to click on the map, and should throw a warning if you run it without clicking on the map. 

This isn't an issue if you run a search previously rather than a selection, which is why I think this is a bug rather than just user error. (i.e. run a search, click the select tool, click feature from results, click go without clicking on the map - it throws a warning saying a selection geometry is required).

**Comment by brentfraser** [comment]
Looks like a bug.  Even though I've chosen Using: "Feature from results", it uses the old/previous selection geometry for my buffer:
![image](https://user-images.githubusercontent.com/1638313/90043723-bac00c80-dc89-11ea-91e2-17083c7da440.png)

**Comment by klassenjs** [comment]
In 3.11 it looks like the result set is getting wiped when the select tool is restarted making select from results not very useful.

**Comment by theduckylittle** [comment]
Fixed in 2f7cfb572227a979b7ed96275e433eb2dd1215ac
