### ISSUE TITLE
Odd Zoom-to after selection 

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#450]
If you do multiple selections in a row there's an odd zoom that happens after then second and later selections. It appears to only happen when you have auto-go set to true and are using a selection option that requires you to finish it by double clicking. (i.e. select by polygon or line, then select again by polygon or line). It doesn't happen with select by point or box.

**Comment by theduckylittle** [comment]
I'm not seeing this bug.

What's your browser / OS combination? I'm also using the fixes from #528 so that could be part of it.

**Comment by chughes-lincoln** [comment]
I'm not seeing this now, I did check it somewhat recently, so I'm assuming it was fixed by #528 or another recent merge.
