### ISSUE TITLE
MULTI LABELITEM

### ISSUE THREAD

**Issue by descholive** [geomoose/gm3#452]
hello

Is it possible to have multi labelitem on one layer ?

ty

**Comment by bblammo** [comment]
Yes.

You can do this on the Mapserver Mapfile, either by using the "wrap" tag
inside of a label, or by using multiple styles, and even by having
different layers that use the same data source to label by.

bobb

**Comment by descholive** [comment]
Are you sure that i can do two label with one layer with wrap tag?
i search information for wrap

**Comment by tchaddad** [comment]
@descholive this is most likely a question for the Mapserver users email list, and not a GeoMoose topic. There are lots of people on both lists that would be able to help with your questions.

You can join the geomoose users list here:
https://lists.osgeo.org/mailman/listinfo/geomoose-users

and the mapserver users list, you can join here:
https://lists.osgeo.org/listinfo/mapserver-users

Would STRONGLY recommend asking your questions there, as GitHub is not a good place to ask (too few people are watching here for one thing). 

Best of luck!

**Comment by descholive** [comment]
TY
have a good day
