### ISSUE TITLE
Identify - Select bug

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#454]
Clicking the identify tool changes the default in the select tool to Point (from Polygon in the demo), even if you do an identify and then do a selection.

To recreate - click identify, then either click on select to see that the default has changed to point, or click on the map to identify, and then click on the select tool to see that the default has changed to point.

**Comment by tchaddad** [comment]
This seems logical to me, if the user has not "ended" the identify tool. however I can see your point. 

I guess the ideal would be that when switching tools, that an "end drawing" happens automagically, without the user knowing to do it?

**Comment by chughes-lincoln** [comment]
That's a good point. I suppose I had assumed that switching tools would automatically end the previous tool. This also happens in the same way with the measure tool (using select after measure retains Draw Line as the default unless you click "End Drawing"). Although the reverse isn't true. If you start the selection, and click measure without "ending" the select tool, it does retain the default measure option.

From a user perspective, I would think that if someone clicks a new tool they would be intending to end the previous tool and would expect to find the default select option.

**Comment by theduckylittle** [comment]
There were some logic assumption changes between 3.0 -> 3.5 that have caused some interesting quirks. There is also a few issues with how the react life-cycle is being used to describe the applications state. This is a bit of a project to revisit but lets keep it documented here.

**Comment by theduckylittle** [comment]
Check on PR #528

**Comment by chughes-lincoln** [comment]
Fixed by #528
