### ISSUE TITLE
Starting a Service at startup breaks refresh

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#455]
If you modify the demo to start the identify tool upon startup, refreshing your screen no longer retains the proper extent of your map (Using the refresh button in the browser, not using the 'Start Over' button). Copying and pasting a url into a different browser window also no longer works.

To replicate, modify the end of the app.js file to include starting a service:

```
    tracker.startTracking();
    hash_tracker.startTracking();

    showTab('catalog');
    app.startService('identify');
});
```

**Comment by chughes-lincoln** [comment]
It appears this no longer correctly starts your specified service on startup.

**Comment by theduckylittle** [comment]
Found some deeper bugs with this one but I think this should handle it:
 - https://github.com/geomoose/gm3/pull/498

**Comment by chughes-lincoln** [comment]
This fixes it for me (both the desired service not starting on startup and the refresh extent issues). Thanks!
