### ISSUE TITLE
Search - Field Required

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#456]
If you select the search tool and click GO without entering anything, it warns you that you need to complete a field (when you've configured the search to throw the warning). (See https://github.com/geomoose/gm3/issues/316). However, if you hit enter instead of GO you avoid this warning. 

I would guess that users in general are more accustomed to searching by hitting Enter rather than clicking a search button (i.e. searching on the web, google maps, etc...) and would run into this and unintentionally search the entire dataset.

**Comment by chughes-lincoln** [comment]
Works great, I think this will help prevent users from using the service incorrectly. Feel free to close it, I'm leaving the issue open right now just because the fix hasn't been pulled yet.

**Comment by theduckylittle** [comment]
Merged. So closing.
