### ISSUE TITLE
Using drawer for tools doesn't retain default option

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#463]
If you use a drawer to group tools in your toolbar, some of your default options are no longer retained.

To replicate add a drawer around measure, identify, and select (the only tools with a default option - although the default for identify is the only option). Now when you click on identify or select, the default 'Using' parameter isn't checked. It is retained for the measure tool. Potentially related to https://github.com/geomoose/gm3/issues/428 and https://github.com/geomoose/gm3/issues/454 (For the latter, if you click measure and then click select without clicking 'End Drawing', it retains the default from the measure tool in your selection).

**Comment by theduckylittle** [comment]
See PR: #528

**Comment by chughes-lincoln** [comment]
Fixed by #528
