### ISSUE TITLE
Generated points

### ISSUE THREAD

**Issue by Freezlex** [geomoose/gm3#464]
Hello,

I wanna know where are declared the point from the draw tools 'cause I don't find wich file made this or wich file is used to move a point ...
In reality I want to move many point in same time but if I don't find how to move one point i cannot move all the point that I want to move sadely
Can you help me ? 
Thanks you for all of your answer and help ^^

**Comment by theduckylittle** [comment]
I'm sorry, I'm not quite clear as to what you are trying to do. The drawing tools are there to make mark-up and sketches. Can you be more descriptive?

**Comment by Freezlex** [comment]
Yes ok sorry no problem I will try to be more precise :
I'm trying to make a tools similar to the "Modify" tools (In case of, this tools is made for modifying a sketch or adding new point on the sketch) but unlike this tool I would not move 1 point at a time but several points in same time .. So I want to know how the "Modify" tools is made (file, declaration, ...) where are the js file to make this new tools by myself.
If it's still not enough clear on problem just tell me and I will try to be again more clear about my attempts

**Comment by theduckylittle** [comment]
I think I understand what you're trying to do and it's an interesting problem. The current drawing tools are all based on the interactions available in OpenLayers. Those are a reduced set than what you might find in a lot of drawing or GIS applications.

To add the behaviour you desire we may need to look at adding an interaction to opens layers, or add some very special exceptions to the way GeoMoose handles the selections.

The GeoMoose code controlling that behaviour is available here: 
 - `src/gm3/components/map.js`
 - The logic is in the `activateDrawTool` function which starts on line 1035 in the master branch.

**Comment by chughes-lincoln** [comment]
It may be worth noting that you'll probably also have to rebuild geomoose to incorporate any changes you're making, rather than just making changes to your initial download. See this guide if you're on Windows: https://geomoose.github.io/gm3/install_on_windows.html

**Comment by Freezlex** [comment]
> It may be worth noting that you'll probably also have to rebuild geomoose to incorporate any changes you're making, rather than just making changes to your initial download. See this guide if you're on Windows: https://geomoose.github.io/gm3/install_on_windows.html

No problem for this part I made some tools for a project wich are working fine, no my real problem is about this point, how they are generated, how they are used and all of the think who make possible to create and move point wich are usefull for my goal. We have been used the Geomoose V2 and now the Geomoose V3 so how it works isn't a problem, but how the tools works is one ... (only for the draw tools obviously) but with the help of @theduckylittle  I think i can find my way 



> I think I understand what you're trying to do and it's an interesting problem. The current drawing tools are all based on the interactions available in OpenLayers. Those are a reduced set than what you might find in a lot of drawing or GIS applications.
> 
> To add the behaviour you desire we may need to look at adding an interaction to opens layers, or add some very special exceptions to the way GeoMoose handles the selections.
> 
> The GeoMoose code controlling that behaviour is available here:
> 
> * `src/gm3/components/map.js`
> * The logic is in the `activateDrawTool` function which starts on line 1035 in the master branch.

Oukay so if I understand right it's managed by OpenLayer and I have to find in the OpenLayer documentation my answer right ?
But Anyway your answer helped me a lot ^^ THX I will try to find
