### ISSUE TITLE
Feature Editing

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/gm3#47]
Implement WFS-T layers.

- Geometry editing
- Attribute editing

We'll use TinyOWS as the example WFS-T server but GeoServer should be tested as well.

**Comment by brentfraser** [comment]
Where are we on this?

**Comment by brentfraser** [comment]
One thing I liked about the original vector editing was the performance when dealing with lots of vectors.  The layer with all the features was rendered with WMS, the user identified/selected a feature (or multiple features?) for editing, the geometry of only that feature was retrieved and presented for editing.  Good stuff.

**Comment by tchaddad** [comment]
Is TinyOWS non-functional? If it still works, maybe incorporating it as a placeholder until the new standard is operational is the best path...

**Comment by theduckylittle** [comment]
My worry is that TinyOWS is not-maintained. The current OGC spec only specifies the way to read features and not the way to write or update them. 

I think tagging this to 4.x is likely the best way to go. I don't want this to fall off the list but it's definitely a feature that could use some sponsorship.

**Comment by jmckenna** [comment]
For the record, some much-needed recent activity for TinyOWS: https://github.com/MapServer/tinyows/pull/94

Also, please keep in mind HTTPS support, in your GeoMoose-WFS-T testing (https://github.com/MapServer/tinyows/issues/93).

**Comment by brentfraser** [comment]
So the current TinyOWS (including PR 94) will not work with a https request?

**Comment by jmckenna** [comment]
I think it needs re-testing, and then update the ticket with test results at MapServer/tinyows#93

**Comment by brentfraser** [comment]
see PR #620
