### ISSUE TITLE
Identify and Internet Explorer 11 and v3.5.x

### ISSUE THREAD

**Issue by mjreynolds** [geomoose/gm3#472]
Identify tool does not yield results when using Internet Explorer 11.  Works with Chrome.  Tested with v3.5.0 and v3.5.1-beta (demo site).

Steps to produce using Internet Explorer 11: Clear cache and load fresh Geomoose desktop demo.  Click Identify tool.  Click anywhere on the map. Super Tab displays "Nothing available to view.  Please click a service to start in the toolbar."

Expected result: shows parcel information.

IE 11 Dev Tools Console reports this error:
"Unhandled promise rejection ReferenceError: 'fetch' is undefined"

**Comment by chughes-lincoln** [comment]
I'm having the same issue when trying to use any of the select tools on Internet Explorer 11 (both on 3.5.0 and the 3.5.1-beta demo).

**Comment by chughes-lincoln** [comment]
This PR fixes the issue for me (though I had to install whatwg-fetch first)

**Comment by theduckylittle** [comment]
It's in the package.json, so it will be included in the builds once the PR is merged.
