### ISSUE TITLE
Demo:  Comment out "Test Grids" in mapbook

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#504]
Used only for testing scale issues (of little use to new users).  And the data is not delivered (yet) with MS4W so layers seem not to work.

**Comment by tchaddad** [comment]
Hmm - the MS4W part of this could be feedback for @jmckenna, could be an option for the installer I suppose...

**Comment by klassenjs** [comment]
Did you use the current gm3-demo-data package?  It works for me in MS4W.

**Comment by klassenjs** [comment]
And it is there because it is important for testing (and hopefully soon automated testing).  There have been a number of scale/resolution/measurement bugs in the past that those layers are meant to guard against.  

New users are expected to create their own mapbook.

**Comment by jmckenna** [comment]
MS4W has its own single package for download that includes the data + software: https://ms4w.com/release/apps/geomoose-3.4.0-ms4w.zip

**Comment by tchaddad** [comment]
Then I think we are good ?

**Comment by jmckenna** [comment]
I was about to create the new 3.6.0 package for MS4W earlier today, until I saw the error reports, so I'm waiting for 3.6.1 to do that

**Comment by klassenjs** [comment]
Waiting for 3.6.1 is a good idea.  It will be today or tomorrow.

**Comment by jmckenna** [comment]
ok thanks.

**Comment by jmckenna** [comment]
I think this ticket is invalid, as general MS4W users will have a single download (or through MS4W installer) that seamlessly installs the data+software.  However for super users that can't wait an hour, ha, for me to upload the new 3.6.x package, they will have to download the separate data package.  Am I correct here @brentfraser ?

**Comment by jmckenna** [comment]
Am I understanding the purpose of this ticket report correctly?

**Comment by brentfraser** [comment]
I love that @jmckenna includes the data with GeoMoose in MS4W.  But the demo site/xml should be a showcase to show all the great features of GeoMoose;  "Test Grids" don't fit too well into that definition.  I do think they are valuable (hence the "comment out"  in the title of issue).  Or maybe we could have a third site in addition to Desktop and Mobile (test? experimental?).

Or maybe the problem is just me.  I was going over the GM interface with a new user, and I stumbled explaining "Test Grids" (and there are at least 4 other definition of "grids" in Web mapping; can we please call Results Grid a Table?).

**Comment by brentfraser** [comment]
@klassenjs I'm a big fan of testing, especially the automated kind (and doc).  I wonder if there is an automated way of adding map-sources (and their layer defs) to a running GM instance.   Have to think about that...

**Comment by elil** [comment]
"Results Table" does sound better than "Results Grid"

**Comment by jmckenna** [comment]
@brentfraser 3.6.1 is now available for MS4W.  Here it is on the MS4W server: https://ms4w.dev/gm3/desktop/   Can you try that demo and let me know if the package needs additional setup/changes?  (I'm still not understanding if you filed this ticket for changes in MS4W or changes elsewhere)

**Comment by jmckenna** [comment]
@brentfraser do you want me to add another link instead of just to "Desktop Application" and "Mobile Application" ?  (referring to the links listed in the GeoMoose section at bottom of https://ms4w.dev/ )

**Comment by brentfraser** [comment]
@jmckenna This is issue is/was specifically for the mapbook.xml as published in the GeoMoose repo: https://github.com/geomoose/gm3/blob/2b5e01b83dcbaa1fa85f5b3ea76790f76fac03d7/examples/desktop/mapbook.xml#L413 and included in the releases published on it's github page.  In my opinion the layers are a distraction on the standard demo site, but still useful when dealing with map scale issues, so I thought commenting them out in the mapbook would be a good solution.

**Comment by jmckenna** [comment]
ok so am I correct that you are not asking for changes in MS4W?   I'm still not understanding.   I am trying to find out if you want me to change the file before distributing it to the community.

**Comment by brentfraser** [comment]
You do plenty already!

**Comment by jmckenna** [comment]
I don't mind commenting the section out, if that helps new users

**Comment by brentfraser** [comment]
I think it would help.

**Comment by jmckenna** [comment]
ok the package has been updated, commented out in mapbook.xml as:
```
        <!-- useful grids for debugging scale issues
        <group title="Test Grids">
            <layer title="1 km grid" src="grids/grid_1km"/>
            <layer title="1 mile grid" src="grids/grid_1mile"/>
        </group>
        -->
```

**Comment by theduckylittle** [comment]
Please don’t make the ms4w version different. Making the downstream packaged version different when we try diligently to make it as drop-in ready as possible invalidates our efforts. 

We actually work pretty hard to make sure everything is in parity and have actually been putting money into doc writers and the time involved to do screenshots, et al. So there’s more than one consequence to making changes like that. Point of fact, we’re geared up to do doc revisions after the dust settles on this version and have a contractor Ed queued up for such. 

If it really is a point of confusion For users then let’s weigh the pros and cons. 

Also, please keep in mind that at this time the flood of requests is coming on like an ambush to @klassenjs and I. But we’re both trying to be responsive under the circumstances.

**Comment by jmckenna** [comment]
ok sorry all.  Trying to keep on top of this.  Can remove easily.
