### ISSUE TITLE
Add legend capbilities to rasterlayers ( WMS, mapserver, ags)

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#511]
Do request for a little thumbnail image and show it in the catalog.  

Here's a snap of Cesium to show the concept (of course GM's layout would be different):
![image](https://user-images.githubusercontent.com/1638313/83181351-fc590680-a0e1-11ea-973a-a598c81562d4.png)

**Comment by theduckylittle** [comment]
@brentfraser - Can you be more specific? We have the ability to specify a fixed legend if you really wanted to do that.

Can you mock something up in a graphics editor for GeoMoose?

**Comment by brentfraser** [comment]
Kinda a low priority, but what I've seen on other mapping systems is the "legend" graphic for tile and image layers is created dynamically based on the current map extent so the user can see what the layer would look like.

**Comment by brentfraser** [comment]
While not "dynamic", I was able to get a nice looking legend for a XYZ tile layer using this in my map-source -> layer:
```XML
            <legend type="html"><![CDATA[
                <img width="100" height="100" src="https://c.tile.openstreetmap.org/12/987/1478.png">
            ]]></legend>
```
