### ISSUE TITLE
templating questions

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#523]
While reviewing my PR for the doc re-org @klassenjs asked some excellent questions regarding the template functionality:

1. So it is perfectly safe if a street name is L'Orient? 

2. It knows to do different substitutions if the {{...}} is in a HTML text node vs. in an href attribute? 

3. GM will never render in a template data that a user can create/change from the web, so we don't have to worry about <script src="bitcoins.evil.js"> showing up in the data?

**Comment by theduckylittle** [comment]
1. L'Orient should be safe.
2. Substitution appears to be no different between the two, so you can hurt yourself.
3. The various common ways of doing <script> attacks seem to be failing. The browser will not load or execute when `<script>` is in the template nor will `document.write(<script...` appear to work either.

**Comment by brentfraser** [comment]
ok by me.  @klassenjs ?

**Comment by klassenjs** [comment]
Sounds good.  I forget where this got left, but hopefully these answers
will find their way into the docs so site implementors know it is covered.
