### ISSUE TITLE
Allow for specifying projections with the Mouse Coordinate control

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/gm3#54]
Right now the mouse coordinates component shows up to three projections:
1. Map X,Y (in the default map projection)
2. USNG
3. Lat, Lon

A user has requested that the control be able to use an arbitrary projection. E.g. UTM-15.  This can be useful for showing maps in web mercator but still allowing the users to resolve features to a coordinate system in which they are more comfortable (State plane, albers, UTM).

**Comment by CaitW** [comment]
1. Would the projection(s) be specified in the mapbook, or are we looking for a control that would let the user select a projection on-the-fly?  
1. Would we continue showing three original projections in addition to the arbitrary projection, or just the arbitrary projection? Multiple arbitrary projections?

**Comment by theduckylittle** [comment]
Let's try and add some depth here:

1. The configuration of the component should happen in app.js.  I'm open as to how to do this but we could have a prop that is literally `projections: ['xy', 'epsg:25916', 'usng']`, the full code would look something like:
```
app.add(gm3.components.CoordinateDisplay, {
 projections: ['xy', 'epsg:4326', 'usng']
});
```

The component will need to recognize "XY" and "usng" as special handlers but all others should just be treated as if they are "reprojections" of the values of "XY".

2. The administrator should be able to choose which projections are available.  I think the array-example above exemplifies a reasonable way to do that.  If the array only has two projections in it, only those two will be shown, if it has four ... let's just go nuts and render all four.  I can see a lot of use cases for two and/or three but if we support an n-number of projections it's up to the user to specify them.

**Comment by theduckylittle** [comment]
The default should stay as it is, that is, if the administrator does not specify any projections, it defaults to xy, 4326, and usng.

**Comment by klassenjs** [comment]
Just a note.  When not full screen or on smaller screens such as my tablet, 3 already is tight for space.  I probably misinterpreted something but I thought the request was that admins could change the XY projection to something else (e.g. map in 3857, XY in UTM) and users could change on the fly to match whatever their other data is in.

**Comment by theduckylittle** [comment]
My interpretation of the request was "XY is useless to us, UTM is more useful." Adding all the controls and what-not for the user to change the projection would get unweildly.  We'd need to add at least one subcomponent and include a lot more projections to make that happen.  Even for this request to work properly we'll want to add some documentation on how to include an new projection into the application.

I agree that three is already tight for space, but allowing any n-number of projections is fine.  If the admin decides to "hurt themselves" by spec'ing four projections that have a bunch of digits they may.  However, I can see a bunch of different reasonably useful configurations:
* One projection: State plane, 4326, UTM, Albers
* Two projections: (State Plane | UTM)  + (4326 | USNG)
* Three projections: Examples above.

I can't really think of a *good* reason for more than that (maybe someone else can?), however, I think an array is the right way to implement it to allow for admins to specify any number of output projections they so choose (from 0 all the way on up to silly numbers).

**Comment by klassenjs** [comment]
Ok

**Comment by klassenjs** [comment]
Do we need a way to specify the label for the coordinates?  If we have more than one X,Y (i.e. not special case like USNG, Lat/Lon). The various EPSG codes probably don't mean anything to most users.

**Comment by theduckylittle** [comment]
Good point, @klassenjs ! Yes, let me amend my thoughts:
```
projections:  [
 {label: 'USNG', projection: 'usng'}, 
 {label: 'UTM15', projection: 'epsg:26915'},
 {label: 'Lat,Lon', projection: 'epsg:4326'}
]
```

If we want to be tricksy hobbitses then we could also have an option for "tranformFn" which would allow the user to pass in a coordinate transformation function as well.

**Comment by CaitW** [comment]
> we could also have an option for "tranformFn" which would allow the user to pass in a coordinate transformation function as well

I like it. Right now, I'm just checking to see if there's a Proj definition already set up for the specified projection string. I'll add this in.

**Comment by theduckylittle** [comment]
We may need to add a function to application or util to "bridge the gap" to allow users to add a projection.

**Comment by CaitW** [comment]
What about allowing the user to specify a proj / wkt string rather than a coordinate transform function? 

Not that both can't be an option, but the former seems simpler for the user as well as simpler to implement.

**Comment by klassenjs** [comment]
USNG would need to be a function (or a special case).  To be correct it needs Lat,Lon,meters per pixel as input and returns a string. (It looks like I cheated in the 3.x implementation for expediency sake and skipped the meters per px, but that really needs to be there to set the length according to the precision).

**Comment by CaitW** [comment]
Right now, it remains a special case - the USNG transform is predefined in the component.

**Comment by theduckylittle** [comment]
@klassenjs : Sorry if I wasn't clear, but if "projection: 'usng'" is set then it should use the special USNG functions.  If those are need in improvement then we can do that separately.  I'd like to see the changes to the component done and since it uses whatever was already there for USNG definition we should be able to fix that independently.

**Comment by klassenjs** [comment]
@theduckylittle Works for me.  I am fine with it living as a special case in the component.  

(If we did go the user supplied function with maybe some common ones provided (or function generators provided (f('espg:4326') -> (g(x,y,z) -> string)) and then could drop the special cases, I was trying to make sure we had enough information to design a complete enough prototype (vs the maybe more obvious f([x,y]) -> [a,b] which wouldn't be enough).)
(Apparently I am thinking in lisp today.  This will make for an interesting day).

**Comment by theduckylittle** [comment]
Served here: 
- https://github.com/geomoose/gm3/pull/74
