### ISSUE TITLE
Translation/lang isn't working

### ISSUE THREAD

**Issue by Freezlex** [geomoose/gm3#544]
I don't know if it's already marked-up but when I try to make a translated application with the `.json` file it's not working like it stay with the `clear-feature-tip` for example but it stay the same for all.
So I think you know about this but I still wanna know if i'm doing it wrong or not 😅
My `fr.json` is over here `carine\src\gm3\lang\fr.json` (from the HTDOCS file)
And in my `app.js` i've added this on the app declaration :
```js
lang: {
        en: './en.json',
        fr: './fr.json' //i've tryied with many file path x)
    }
```

**Comment by Freezlex** [comment]
Ok after some tryies i've noticed than when I put my new lang into the `carine\src\gm3\i18n.js` file it works fine, but when I put it into the `app.js` it didn't works with the right syntaxes

**Comment by theduckylittle** [comment]
The fr.json file should go next to the app.js file.

- https://geomoose.github.io/gm3/howto/add-a-language.html

I'll clarify that in the documentation!

**Comment by Freezlex** [comment]
Huuuuum okay that was so obvious 😅
So we cannot link it to another location ? like i've tried tu put something like `..\geomoose\src\gm3\lang\fr.json` annnnd ... nothing

**Comment by klassenjs** [comment]
Putting it in `/src/gm3/lang` is correct for adding the language officially.  Did you update i18n.js and rebuild GeoMoose?

The reason the add-a-language recommendation is to put custom translation files next to app.js is so it doesn't get overwritten or conflict when GeoMoose is updated.

**Comment by Freezlex** [comment]
Yeah when I put it directly in the `i18n.js` it works perfectly, this is when I try to add it into the `app.js` and locate the file into `..\geomoose\src\gm3\lang\fr.json` that it doesn't works ... But anyway you solved my both issues thanks a lot 👍

> Putting it in `/src/gm3/lang` is correct for adding the language officially. Did you update i18n.js and rebuild GeoMoose?
> 
> The reason the add-a-language recommendation is to put custom translation files next to app.js is so it doesn't get overwritten or conflict when GeoMoose is updated.

**Comment by elil** [comment]
> I don't know if it's already marked-up but when I try to make a translated application with the `.json` file it's not working like it stay with the `clear-feature-tip` for example but it stay the same for all.
> So I think you know about this but I still wanna know if i'm doing it wrong or not 😅
> My `fr.json` is over here `carine\src\gm3\lang\fr.json` (from the HTDOCS file)
> And in my `app.js` i've added this on the app declaration :
> 
> ```js
> lang: {
>         en: './en.json',
>         fr: './fr.json' //i've tryied with many file path x)
>     }
> ```

Hi @Freezlex, I'm a little late on this but would you be willing to contribute your fr.json translation to the GeoMoose project?  If so, can you attach the file in a new issue or here (or perhaps a .zip of it) and can you confirm that you are contributing this under the license here, https://github.com/geomoose/gm3/blob/master/AUTHORS?

PRs also welcome here, https://github.com/geomoose/gm3/tree/master/src/gm3/lang and add your self to the Translators section of the Authors file https://github.com/geomoose/gm3/blob/master/AUTHORS in the PR.
