### ISSUE TITLE
A summary of GeoMoose's current server protocol support

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#547]
**This table is now kept up to date at https://docs.geomoose.org/3.x/protocols.html**

   I'm close to wrapping up my exploration of GeoMoose's current server protocol support.  Below is a summary I intend to put in the GeoMoose doc so new users can see at a glance what is possible .  I've left out SRS restrictions (a topic for another table), and Brian's excellent summary of possible ArcGIS Server protocols (see https://github.com/geomoose/gm3/issues/517).
  
 Hopefully the table will include links to detailed descriptions, in the doc as pages are added.
  
 Comments are appreciated!

**(Table updated 2021-May-26)**

Data Protocol Support
---

Web Resources
----

| Data Source Protocol  | Protocol Type  | mapsource type|  Display | Feature Info <br>"identify"   | Search<br>(by attrib. values) | Select<br>(by spatial feature) |
| --------------------- | ----           | ------------  | ---------| ----------------------------  |--------|--------|
|**Image Tile Servers** | XYZ (e.g OSM)) | xyz           | Yes      | No                            | No     | No     |
|                       | Bing           | bing          | Yes      | No                            | No     | No     |
|                       | Google         | _no support_  |          |
| **OGC**               | WMS: v1.1.1    | wms           | Yes      | Yes (no highlight<sup>1</sup>), INFO_FORMAT=GML | No, use query-as ->vector<sup>1</sup> | No, use query-as ->vector<sup>1</sup>     |
|                       | WFS: v1.1.0    | wfs           | Yes      | Yes, INFO_FORMAT=GML, GeoJSON | Yes    | Yes    |
| **UMN MapServer**     | "classic" CGI  | _no support_ (use its WMS,WFS protocols)  |
|                       | WMS: v1.1.1  | mapserver  |Yes   |Yes (no highlight<sup>1</sup>),  INFO_FORMAT: application/vnd.ogc.gml|
|                       | WFS: v1.1.0    | mapserver-wfs  |Yes   |Yes, outputFormat="text/xml; subtype=gml/2.1.2" |
| **Arc GIS Server** v10+ | MapServer<br>/export?f=image | ags | Yes  | No<sup>2</sup> | No<sup>2</sup> | No<sup>2</sup> |
|                       | MapServer<br>/tile/{z}/{y}/{x} | xyz | Yes  | No     | No     | No     |     
|                       | MapServer<br>/query?f=json     | ags-vector | Yes | Yes    | Yes    | Yes    |
|                       | FeatureServer<br>/query?f=json | ags-vector | Yes | Yes    | Yes    | Yes    |
| **Vector files**      | GeoJSON        | geojson       | Yes      | Yes                          | Yes    | Yes    |

Other Data Source Types
----
| Data Source Protocol  | File Format  | mapsource type | Display | Feature Info <br>"identify"  | Search | Select |
|-----------------------| -----------  | -------------- | ------- | ---------------------------- |--------|--------|
| Local file load/save  | GeoJSON      |  vector        | Yes     | Yes                          | Yes?   | Point only |
|                       | KML          |  vector        | Yes     | Yes                          | Yes?   | Point only |
| Internally Generated   | n/a             |  usng             | Yes      | No                          | No   | No |

1. Use two mapsources, one wms (for display), the other wfs for the query. Add a "query-as" attribute to the wms layer
2. GeoMoose does not support this even though the layer on the AGS server can be configured to have "Supported Operations: Query"

**Comment by klassenjs** [comment]
That's a handy table!

Do you think the target audience is familiar with what a XYZ tile is?  Should we give some examples of services that implement XYZ tiles? (I'm thinking as a footnote/discussion, not directly in the table).

Should we link from the specifications to documentation for the specification (if readily available)?

Should we link from the table to the GeoMoose documentation for each layer type (probably in the mapsource column)?

**Comment by brentfraser** [comment]
Yes, I expect we'll give examples / lists / references to tile servers.  Links to the specs would a good idea (I've had to do some searching to find them!)  And absolutely we would link to details in the GeoMoose doc, and maybe some links to to the demo.  

I've been putting together another example ("test") in addition to "desktop" and "mobile" to show connections to the various types of servers, legend options, and vector styling.  See PR #545 

![image](https://user-images.githubusercontent.com/1638313/84954557-d2787b80-b0b2-11ea-98f9-03f3cbf07673.png)

**Comment by tchaddad** [comment]
This approach of a template organized by examples of how to connect to each service type is super valuable. Especially to users who are "shopping" UIs for something that has the correct combination for what they need. Definitely a great addition to docs!

**Comment by elil** [comment]
Yes, very useful.  You may want to consider adding to OSGeoLive as well, https://github.com/OSGeo/OSGeoLive-doc/blob/master/doc/quickstart/geomoose_quickstart.rst

**Comment by brentfraser** [comment]
This table is now kept up to date at https://docs.geomoose.org/3.x/protocols.html
