### ISSUE TITLE
Search Runways Tool

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#560]
Tool has no Icon

**Comment by klassenjs** [comment]
And this is really airfields not runways.

**Comment by brentfraser** [comment]
How does a tool get an icon?

And title is from the data source https://gis2.co.dakota.mn.us/arcgis/rest/services/DCGIS_OL_Transportation/MapServer/21
Layer: Airport Runways (ID: 21)
But it can be named whatever we want...

**Comment by elil** [comment]
The search runways tool may not be working currently

**Comment by brentfraser** [comment]
Yep. It is broken in the full demo.  The map-source name in the mapbook is wrong as it does not correspond to the search parameter in the app.js.   The parameter uses the name in the mapbook-test-servers.xml, so search runways works in the Protocols demo.  I'll change mapbook.xml.

**Comment by brentfraser** [comment]
PR #821

**Comment by chughes-lincoln** [comment]
It looks like the URL for runways (airfields) now needs updating. It's now layer 42, not 21 - https://gis2.co.dakota.mn.us/arcgis/rest/services/DCGIS_OL_Transportation/MapServer

**Comment by tchaddad** [comment]
ooh thanks @chughes-lincoln , I fixed these service links in the services demo mapbook, but didn't check the others, I'll circle back.

**Comment by tchaddad** [comment]
closing as complete
