### ISSUE TITLE
AGS - Identify

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#565]
It looks like there's an issue with identifying ags-vector layer that occurs when the ags-vector layer has any identifiable layers beneath it in the `<map-source>` section of the `mapbook.xml`. It still allows you to identify the ags-vector layer and any other identifiable layers above it in the map-source.

To replicate in the demo, modify the `mapbook.xml` to move the Runways layer (ags-vector-dc21) above the parcels layer. Then when identifying in the demo you can see that you can no longer identify anything below the Runways layer:

<img src="https://user-images.githubusercontent.com/43766648/86266343-eb386500-bb79-11ea-96a0-d82f1e88ae5d.png" width="250" height="250">

**Comment by brentfraser** [comment]
I think this is fixed in PR #587

**Comment by chughes-lincoln** [comment]
Thanks Brent, it looks like this was fixed in the PR you mentioned (specifically moving the identify template from the layer with the query-as parameter to the wfs mapsource). The only odd behavior I've noticed is that the identify behaves differently when an ags layer is on. Normally it returns results at the point you choose. With an ags layer on in the catalog, it returns results at a small box around the point, so when you click near the border of a polygon, it will return results on both sides of the boundary.

Now that I think about it, it may due to this PR https://github.com/geomoose/gm3/pull/539 to fix an issue with identify on ags layers. I'm not sure how much of an issue it is but I thought I'd mention it.

**Comment by brentfraser** [comment]
Yeah I think #539 was to address the problem of requesting an "intersection" of a point search  with point features, so a small square polygon was constructed around the search point (bit of a hack).

I've been thinking of creating a table of the search-geom vs feature-geom for the three data sources of: WFS, AGS-vector, and browser vectors (#571 ).  Then fill in the spatial query predicate required for each protocol.  Could be a lot of work for a small pay-off.
