### ISSUE TITLE
Print Before Preview Renders

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#567]
Currently if the user prints before the print preview finishes rendering (i.e. if you change to highest resolution, or you have intensive data such as imagery), a partially rendered map will be printed.

It would be nice if the print waited for the preview to finish rendering before printing. While this is partially just an issue with impatient users, there is also the larger issue of the user not realizing that the preview hasn't finished rendering (it's obvious that imagery hasn't appeared, it's less obvious when a vector layer hasn't shown up yet above imagery).

**Comment by klassenjs** [comment]
The whole genesis of the print preview thing was a trick to get the user to pause long enough for the map to render to the background canvas before they click print to render the PDF.... because there wasn't a reliable way to know when the background render finished.

**Comment by tchaddad** [comment]
So can we not just add a line of text (or alter the button text) to ask people to wait?

**Comment by chughes-lincoln** [comment]
Adding a note to the print preview page that you need to wait for the preview to render would definitely help. It would at least give the user the information they need to use it properly.

**Comment by tchaddad** [comment]
If GeoMoose can detect when the preview is fully loaded, another option would be to keep the print button greyed out until that point, and then change the color to green when the print is possible.

if you want to get fancy...

**Comment by elil** [comment]
Some low-tech options would be a visual 10 second countdown/wait (or making the number of seconds configurable in the mapbook).

**Comment by theduckylittle** [comment]
This should now be fixed in the 3.11 branch commit e64001f872e1a77a3848a7b91feb003589d8d735
