### ISSUE TITLE
Highlight on Identify doesn't work when using query-as

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#576]
In the demo (including the on-line demo), doing an Identify on the Parcel layer works, except it does not highlight the parcel polygon.

**Comment by theduckylittle** [comment]
It's not supposed to since it supports WMS identify.

**Comment by brentfraser** [comment]
Yes, but it could since properties and geometry can be returned from the single point query on WMS (I think?)

**Comment by brentfraser** [comment]
And it this specific example it uses "query-as" on WFS layer for Select and Search so it could do it for Identify if a WMS GetFeatureInfo query can't get geometry.

**Comment by theduckylittle** [comment]
Not really, and WMS doesn't respond consistently. Identify tries to allow
the least common denominator of services.

**Comment by brentfraser** [comment]
Yes I see that only the bounding box extent is in the WMS spec, but most/soem of the WMS server (Mapserver, GeoServer, and maybe QGIS) can return the geometry as an option.  At any rate, it would seem reasonable for the WMS query-as -> WFS combo to highlight on Identify.

**Comment by jmckenna** [comment]
MapServer WMS cannot return geometry.  Optionally MapServer WMS service can be configured to return all attributes, but not geometry.   The client sends the bounding box to the server, and the map image + attributes are returned.  There is no mention of extent as part of the response according to the spec (pdf: https://portal.opengeospatial.org/files/?artifact_id=14416)

PS. please always use the correct spelling of "MapServer"

**Comment by jmckenna** [comment]
I stand corrected, it's not part of the WMS spec, but now I remember that you can use OUTPUTFORMAT to have GetFeatureInfo return geometry, such as geojson.   :)

Early morning brain, need coffee.

**Comment by brentfraser** [comment]
Hmm.  Reading gml_geometries description at https://mapserver.org/ogc/wms_server.html#layer-object-metadata implies that it can, but I haven't tested it.  And it is obscure; I found it referenced in a [closed Issue](https://github.com/mapserver/mapserver/issues/2989).  

Yes, more coffee.

**Comment by brentfraser** [comment]
And for it to be useful client s/w would have to use it.  I appreciate Dan's desire to code to the lowest common denominator (in this case the WMS spec), but I just feel all warm and fuzzy when the the parcel I clicked highlights!

**Comment by theduckylittle** [comment]
It can be done.

But the intention of identify in the demo is toshow how to work with the
least capable services.

For a specific application or set of configurations, it is extensible but
there are many WMS providers, which only even return HTML.

**Comment by brentfraser** [comment]
For the demo, the solution is to move the 
`<template name="identify" src="./templates/parcels.html" />`
from the WMS Parcel map-source to the WFS Parcel map-source.  

I'm happy.

**Comment by jmckenna** [comment]
good catch with gml_geometries, I think my outputformat mention is for wfs, tricky indeed.

**Comment by tchaddad** [comment]
Ha - I missed this whole thread, but would have added that WMS was always intended to be a cartographic service, and so extending it to serve geometries will always be outside of the spirit of the spec, even if different servers allow it to happen in different ways.
