### ISSUE TITLE
WFS  spatial queries hard-coded to expect "geom" as the geometry name

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#579]
Looking at [wfs.js](https://github.com/geomoose/gm3/blob/2e61b05bd9a593a3e04ef0495553fc86ec1ca4b2/src/gm3/components/layers/wfs.js#L74), I see that GeoMoose expects/requires the WFS server layers to have the geometry property named "geom".   Is there a way to over-ride this?

**Comment by brentfraser** [comment]
MapServer doesn't seem to care what the geometry column is called in the query
`"<Intersects><PropertyName>geom</PropertyName>"`
I guess it either ignores it or if the column doesn't exist it just uses the geometry column that does exists.

GeoServer seems to care:
Error
Illegal property name: geom for feature type

**Comment by brentfraser** [comment]
Changing the code to be 
`const geom_field = null;`
seems to work a little better.  OpenLayers sends:
`<Intersects><PropertyName>the_geom</PropertyName>`
which just happens to be the geometry column name of my server's layers.  But I can see that this would not work for all servers.

**Comment by brentfraser** [comment]
Looks good.  But would the param be sent on every request? Or not because it has no "value" attribute?

**Comment by theduckylittle** [comment]
I should double check my syntax for the XML. :laughing: 

It's doesn't get sent because I've also added a new exclusion list for parameters that should not be serialized.

**Comment by brentfraser** [comment]
Here's a server url for testing
https://mrdata.usgs.gov/wfs/sgmc2?service=WFS&version=1.1.0&typeName=ms:Structure&request=getFeature&maxFeatures=1

unfortunately, it only generates geometry in EPSG:4326, so we may need some GM code enhancements to deal with that.

**Comment by brentfraser** [comment]
I've tested with
```
		<config name="geometry-name" value="the_geom"/>
```
and it works well.
