### ISSUE TITLE
Set maxZoom for map

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#583]
I'd like to set the maximum zoom level of my map.  This is have a better result when:
 - tile servers send bogus tile images for high zoom levels
 - Zoom-to-results on point features zooms in waay too much.

Any thoughts on how to do that?

I've tried:
```
var app = new gm3.Application({
    mapserver_url: CONFIG.mapserver_url,
    mapfile_root: CONFIG.mapfile_root,

    map: {
        maxZoom: 19,
        scaleLine: {
            enabled: true,
            units: 'imperial'
        }
    }

});
```
but no go.

**Comment by brentfraser** [comment]
So in [map.js](https://github.com/geomoose/gm3/blob/2e61b05bd9a593a3e04ef0495553fc86ec1ca4b2/src/gm3/components/map.js#L912) I added:

```
        if(this.props.config.maxZoom) {
            view_params.maxZoom = this.props.config.maxZoom;
        }

        // initialize the map.
```

with
```
var app = new gm3.Application({
    mapserver_url: CONFIG.mapserver_url,
    mapfile_root: CONFIG.mapfile_root,

    map: {
        maxZoom: 19,
        scaleLine: {
            enabled: true,
            units: 'imperial'
        }
    }

});
```
I was able to get the desired behaviour, but it seems like such a hack...

**Comment by theduckylittle** [comment]
It's now

```
....
map: {
  view: {
    maxZoom: 19,
  }
}
...
```

But also allows setting the center, minZoom, maxZoom, and defualt zoom there as well.

**Comment by brentfraser** [comment]
Looks good!
