### ISSUE TITLE
Query results: Move Zoom-to tool to tool bar

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#588]
Move the big zoom-to-results "button" to a smaller icon on the results tool bar (along with the clear-results icon).  So instead of:

![image](https://user-images.githubusercontent.com/1638313/90029728-6ceed880-dc78-11ea-9999-8cc19a4227c7.png)

Have:

![image](https://user-images.githubusercontent.com/1638313/90029507-2dc08780-dc78-11ea-9be3-ab9c29c5bbfb.png)

**Comment by brentfraser** [comment]
To move the zoom-to-results tool into the tool bar:

```
diff --git a/src/gm3/components/serviceManager.js b/src/gm3/components/serviceManager.js
index 6b7eaf8..bae20b8 100644
--- a/src/gm3/components/serviceManager.js
+++ b/src/gm3/components/serviceManager.js
@@ -150,13 +150,6 @@ class ServiceManager extends React.Component {
                     <div className='label'>{this.props.t('layers')}</div>
                     <div className='value'>{ layer_count }</div>
                 </div>
-
-                <div className='results-info-item zoomto'>
-                    <div className='label'>{this.props.t('zoomto-results')}</div>
-                    <div className='value' onClick={() => { this.props.zoomToResults(query); }}>
-                        <span className='icon zoomto'></span>
-                    </div>
-                </div>
             </div>
         );

@@ -165,6 +158,13 @@ class ServiceManager extends React.Component {
                 <div className='results-header'>
                     { this.props.t(service_title) }
                     <div className='results-tools'>
+                        <i
+                            title={this.props.t('zoomto-results')}
+                            className='icon zoomto'
+                            onClick={() => {
+                                this.props.zoomToResults(query);
+                            }}>
+                        </i>
                         <i
                             title={this.props.t('results-clear')}
                             className='icon clear'

```
and
```

diff --git a/src/less/results.less b/src/less/results.less
index 6d2cdcc..8596224 100644
--- a/src/less/results.less
+++ b/src/less/results.less
@@ -86,7 +86,7 @@
         display: flex;

         .results-info-item {
-            width: 30%;
+            width: 50%;

             padding: .25em;
             margin: 5px;

```

**Comment by tchaddad** [comment]
I don't necessarily have a strong opinion on this, but this change would seem like it might be unfriendly to folks using the UI on a mobile device, if that matters to you...

**Comment by brentfraser** [comment]
It's very important to me.  I need to review the mobile demo GUI in detail for usability. I see the trash can Icon is in the toolbar:
![image](https://user-images.githubusercontent.com/1638313/90073133-ec4ecd00-dcb5-11ea-8225-632735d5665a.png)

**Comment by tchaddad** [comment]
Yes - well that could be a second problem to be aware of: moving a small icon next to the trash can is kind of asking for a fat-fingered mistake, where the user accidentally trashes the result rather than zooming to it. 

Only pointing it out as a potential UI issue. If you have a strong business need it could override these concerns.

Curious: are you trying to win back some screen space so that you can use it for something else? or just trying to be more compact? "Zoom to" seems less relevant to Identify than to Search, since the user had to click the item to identify it in the first place, so maybe zooming is irrelevant and doesn't need to be there at all?

**Comment by brentfraser** [comment]
All good points.  I was just trying to be consistent: tools in the tool bar, results in the results pane.  Not a huge deal.  And it was spawned from an issue (#369) speculating about putting tools in the toolbar to control the visibility (show/hide) of the grid/table

**Comment by theduckylittle** [comment]
3.11.0 does not have a trash can icon in the toolbar. Does that change anyone's feelings? :joy:

**Comment by brentfraser** [comment]
So no more clear results?

**Comment by theduckylittle** [comment]
Pushed a proposed change!
