### ISSUE TITLE
add `xyz=` hash parameter

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/gm3#592]
Use lat / lon / zoom instead of meters rez / x / y.

**Comment by chughes-lincoln** [comment]
Out of curiosity, would this change how the URL's currently work? Or just add the ability to overwrite the current URL's if desired?
(Meaning if an administrator created URL's to specific locations in their map based on meters rez /x / y, would this break their URL's?)

**Comment by tchaddad** [comment]
@chughes-lincoln I think since it is a different parameter being added, it would not collide. At least if this is related to the previous conversation here: https://github.com/geomoose/gm3/issues/600

so "loc=" and "xyz=" would be 2 different ways of getting to a location

**Comment by klassenjs** [comment]
See PR #644
