### ISSUE TITLE
Issue with Bing Geocoder not working on desktop version

### ISSUE THREAD

**Issue by goo160047co** [geomoose/gm3#597]
Cannot get the Bing Geocoder to work. Connect/switch the index.html to geocoder-bing.js  and path to  gm3\htdocs\geomoose\dist\services folder and change out this line in my js file  app.registerService('geocode', OSMGeocoder, {}); to app.registerService('geocode', BingGeocoder, {}); Once ran it just spins and never finishers.  I was wondering if this is a known bug?  I do have a bing API key for my imagery in the .xml file do I need to place a separate key somewhere for the geocoder service? Could not find a spot in the geocoder-bing.js to place it.

**Comment by brentfraser** [comment]
The Bing map source in the mapbook.xml is only for the display of Bing map tiles.   Try adding the key to the registerService as an option:

    app.registerService('geocode', BingGeocoder, {key='my_bing_api_key' });

Make sure you change my_bing_api_key to your key value.
