### ISSUE TITLE
node_modules  are included in the htdocs/mobile directory

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#599]
In the [Nightly Development Builds](https://www.geomoose.org/download.html), the `node_modules ` are included in the htdocs/mobile directory.  Is this necessary?

**Comment by klassenjs** [comment]
Yes

**Comment by brentfraser** [comment]
Interesting.    I see that `mobile/node_modules/jquery/dist/jquery.slim.min.js`, and `mobile/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js` get loaded in the mobile example (about a 150 kb).
