### ISSUE TITLE
GM not working in Firefox 81.0.2 with DuckDuckGo Privacy Essentials extension

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#607]
But it works if in FF I turn off the DuckDuckGo Privacy Essentials extension.

**Symptom**
Using the demo GM stops after it shows the basic HTML and does not show the Catalog entries.

**Investigation**
After I switch the index.html to use geomoose.js instead of geomoose.min.js, the FF console shows an error in GM's[ index.js line 94](https://github.com/geomoose/gm3/blob/1e0978c6f8e8a4337da367c094d22d25c91d26c8/src/index.js#L94)

```
    for (var i = 0; i < scriptTags.length; i++) {
        var src = scriptTags[i].getAttribute('src');
        if (src.indexOf('geomoose.js') >= 0 || src.indexOf('geomoose.min.js') >= 0) {
            distPath = src.split('/').slice(0, -1).join('/');
        }
    }
```

The error is at the `if(src.indexof` because the first of the three `scriptTags[]` does not have a 'src' attribute so `src `is null. While the other two  `scriptTags[]` look legit (gemoose.js and config.js), this bit of JavaScript looks odd.  It's about 25 lines of things like `Object.defineProperty(navigator, "doNotTrack", { value: "unspecified" });` (Thanks, Privacy Essentials extension!)

**Fix**
Anyways, the fix is to test if src is not null prior to the `(src.indexOf` test.

**Comment by klassenjs** [comment]
Is the DDG extension injecting an anonymous script into the page?  That seem like an odd thing to do and a bit of a difficult environment to target/test if the browser is rendering a different page than we coded.

However, adding the null check in the name of defensive programming seems like a good thing to do.

`if(src && src.indexof...`

**Comment by brentfraser** [comment]
Those were my thoughts too.  I think there is a pitched battle between sites trying to harvest info about users and browsers/users trying to prevent it.

And like you say, we need to code to expect the unexpected.
