### ISSUE TITLE
Limiting Extent of App

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#609]
Per https://geomoose.github.io/gm3/howto/set-maxzoom.html, the ability to set the minimum zoom, maximum zoom, and extent of the application was added. 

Copying this code to my demo application (after pulling all the other recent changes from github) correctly sets the minimum
and maximum zoom, but doesn't appear to set the extent of the app (users can still scroll laterally outside of that extent).

**Comment by theduckylittle** [comment]
Embarrassingly easy fix!

**Comment by chughes-lincoln** [comment]
Made that modification on my end and it's working for me now. Thanks!
