### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#610]
Fix linking issues which makes it look like we have less documentation that we actually do.

**Comment by brentfraser** [comment]
I can work on this.  I guess the requirement is to move the sub-lists to the main page,  e.g. all (or most of) the links under the "Adding Layers" bullet.

**Comment by theduckylittle** [comment]
I have a script to do a mass format conversion to RST. I’ll run that today
and we can go from there.

**Comment by brentfraser** [comment]
sounds good.

**Comment by theduckylittle** [comment]
Hey Folks,

New branch is available here:
 - https://github.com/geomoose/gm3/tree/docs-to-rst

I've merged in my initial automated conversion. I've done the following:

1. Run `pandoc` to convert MD to RST.
2. Ran a small script that changes links from <something.md> to
<something.rst> to fix relative links. It would be nice to be able to both
use the GitHub browser and the website's sphinx variant but I think
sacrificing the former in favor of the latter is a better choice.

Next steps:

1. Setup some test landing spot with sphinx running for collaborative
testing.
2. Fix the TOC's.
3. Make the sphinx configuration closer-match the website.

**Comment by brentfraser** [comment]
Hi @theduckylittle.   I've had better success with:
```
- :doc:`Developing on Windows<./install_on_windows>`
```
instead of :
```
-  `Developing on Windows <./install_on_windows.rst>`__
```
Unless there's a trick?

**Comment by brentfraser** [comment]
That is with Sphinx I mean.  I see that the `.rst` flavor works with GitHub.

**Comment by theduckylittle** [comment]
I don't think there will be a happy medium for the two platforms so I'll defer to being able to publish properly with sphinx. Working on updates including the indexes. Markdown is a little more flexible that way so the diff will look a little larger than it really is due to shuffling cards on the deck.

**Comment by brentfraser** [comment]
Let me know when you're done.  I need to do some re-org and add some content.

**Comment by theduckylittle** [comment]
New branch!

https://github.com/geomoose/gm3/pull/612

This one works!

**Comment by brentfraser** [comment]
Is #612 going to be merged into master soon?

**Comment by theduckylittle** [comment]
You should be able to bring the branch in locally and create a pull request
against the branch.

**Comment by brentfraser** [comment]
From your personal fork?

**Comment by klassenjs** [comment]
Since the github pages site broke, and the sphinx site was working I merged the PR and I'm going to close this.  Future doc updates/opening new issues always welcome.
