### ISSUE TITLE
Adding it.json

### ISSUE THREAD

**Issue by flaviorigolon** [geomoose/gm3#613]
I'd like to share the it.json file for italian language translation which I attach here; surely it can be improved but it could be a start point.
[it.zip](https://github.com/geomoose/gm3/files/5677989/it.zip)

**Comment by elil** [comment]
Great, thanks for getting the Italian language translation started!  

Are you contributing this under the license here, https://github.com/geomoose/gm3/blob/master/AUTHORS?

**Comment by flaviorigolon** [comment]
Oh yes! I' ve read it and I surely agree.
Thanks to you.

Flavio

Il Ven 11 Dic 2020 13:07 Eli L Adam <notifications@github.com> ha scritto:

**Comment by theduckylittle** [comment]
All merged in! Thanks everyone!
