### ISSUE TITLE
Discussion: Updating Examples to Add Editing

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/gm3#631]
This issue is meant to allow a forum for discussing the integration of the new GeoMoose editing functionality (see #620 ) into the GeoMoose examples.

## Current state

Currently, we have two examples. One example uses very plain Javascript and is intended for desktop browsers. The other example uses jQuery mobile and is intended as an example of a mobile version of GeoMoose. Both versions can be fed by the same mapbook and are generally considered to be "front-end" examples to the GeoMoose library.

## Proposal

We add a third example that show cases editing. In the end we would ship three directories in `examples/`:
1. `desktop/` - This will remain largely unchanged from what is currently in main.
2. `mobile/` - This will also remain largely unchanged.
3. `editing/` - This will essentially be the `desktop/` example but with a much more focused mapbook. It will have significantly fewer layers and possibly fewer configured default services. Users and administrators will see exactly what is necessary in order to do editing. As a "3b": We could tune this demo to be an example of how to run on GeoServer.

Cons:
 * We have strived to make the "desktop" example very complete. This would then move an example feature OUT of the desktop demo.
 * People may see the editing features as mutually exclusive to others.
 * It will require additional packaging and build system support.

Pros:
 * It makes it easier to test editing specific features.
 * The separate demo means we do not _need_ to ship that demo in all packages.
 * As the editing requires some sort of database and additional services, it could be installed but not "operable" until the user follows the set of necessary instructions.

## Please refrain from the following sub-threads:

* Renaming "examples/" even though this will be a big release, it is currently backward compatible. There could be a number of arguments that moving the examples necessitates a major version change or more work. Let's please set that aside for now.
* GeoServer vs. TinyOWS/MapServer. Ideally, we support both configurations. Productive chat about the way to do that is welcome, mudslinging one project vs another is not. 

## Please DO keep the following in mind:

* This is *largely* a volunteer effort. From the development to the deployment to the packaging. No one is looking to place blame or burden on anyone else. If something will create great friction in a work process then call it out but also try to describe how it can be helped.
* Assume benign intent. No one in the discussion is trying to be critical but most of the comments made below will be done between trying to get through busy days and get work done. If it sounds harsh, take a moment, consider the other, then write.

Thanks everyone!

**Comment by bblammo** [comment]
I would like to be able to store, and describe the edits in Postgres as an example.  I know there is an overhead with regard to setting up a Postgres instance, but it could be set to clear itself with data older than some short period, like 10 min- an hour . . .

Describing the data store and GeoMoose examples would be easier, and seems more flexible with regard to integrating into other workflows.

**Comment by brentfraser** [comment]
@bblammo Good idea.  In fact if you use GeoServer as your WFS-T server you can use a GeoPackage file as your data-store (geomoose/gm3-demo-data#5).  While I wouldn't recommend using GeoPackage as a production data-store, it would likely be fine for a demo.

**Comment by jmckenna** [comment]
I volunteer to handle packaging the editing demo for Windows/MS4W users.  Thanks for being open to all solutions.   Following this discussion.

**Comment by elil** [comment]
3 seems unlikely to occur in the wild.  It does make editing configuration more clear, simple, and perhaps easier to understand.  There will be testing benefits to this method but also testing drawbacks (since this is an unlikely configuration and doesn't test for interactions between editing and other services and tools).

An option 4 might be `editing/` that is the fully configured desktop with editing.
An option 5 might be `desktop/` that is fully configured desktop with editing that is commented out.  
An option 1 `desktop/` with editing added in is presumably what we are avoiding, the complication and complexity of editing being added to the main default which most people won't care about

**Comment by brentfraser** [comment]
@jmckenna Thanks for the volunteering!  My goal is to have a simple path for admins to  try out editing.  In my perfect world it would be some kind of one click/command install to get a WFS-T server + data.   So far my choices were:

1. install GeoServer plus supply a sample GeoPackage of vectors
2.  TinyOWS + instructions on loading data into PostGIS.

But I see that OGR actually supports WFS-T (https://gdal.org/drivers/vector/wfs.html) .  I might look into that.

**Comment by theduckylittle** [comment]
I was thinking that the editing example could be "full fat" but maybe focused on a GeoServer-based install.  We could backport that into MapServer and WFS-T. There are definitely some quirks in GeoMoose that make assumptions about the WMS being MapServer . I feel we could learn a lot by actually exercising how other services return data using the standards based approach.

While not WFS-T, there is a Python implementation of the OGC features API, which would be another exploratory project and likely out of scope for this discussion: https://www.osgeo.org/projects/pygeoapi/

**Comment by brentfraser** [comment]
@theduckylittle  I assumed we would leave the existing Mapserver based layers  (and Mapserver) in place, and the enabling/configuring of editing would be an option described in some documentation.  But I like your comment about learning a lot using GeoServer.

**Comment by brentfraser** [comment]
While I was initially in favour of just added a couple of editing layers to the existing "desktop" example (as it would prevent duplication of css and other files), I think we would be able to do a more substantial editing example if there was a separate "editing" example.  

In the extended editing example we could show a simple login form and have some server-side scripting to deliver a mapbook based on the the login.  Not sure about the GeoServer security.

**Comment by brentfraser** [comment]
@theduckylittle  Maybe have two separate mapbooks: `mapbook-geoserver.xml` and `mapbook-mapserver.xml` (for tinyows).

**Comment by brentfraser** [comment]
And the good news is editing with TinyOWS works just fine!

**Comment by brentfraser** [comment]
Here's a snap of my testing site to get the creative juices flowing:

![image](https://user-images.githubusercontent.com/1638313/110498164-51d03400-80b4-11eb-9271-38636be30217.png)

@elil Your comment made me realize I need to test editing layers with the other functions such as Search and Select

**Comment by brentfraser** [comment]
So my proposal is basically (@elil 's Option 5 in his comment above):

- In the desktop example's mapbook.xml, add COMMENTED-OUT point, line, and polygon mapsources and catalog entries for editing.
- The mapsources will point to a GeoServer instance (not included in the GeoMoose package).
- GeoMoose documentation (a How-To) will show how to install, load, configure GeoServer to serve the point, line and polygon demo data for editing.
- GeoMoose documentation will also include instructions on loading and configuring the demo data for MS4W's TinyOWS.
- The GeoMoose On-Line Demo will include the working point, line, and polygon editing layers.

Comments?

**Comment by klassenjs** [comment]
As a practical matter, I'd really like to keep the current structure where mapbook.xml is unchanged between git and on https://demo.geomoose.org.  Right now the only file that is modified for https://demo.geomoose.org (and for the gm3-examples-* packages) are the `config.js` files.  A separate folder for editing (or at least a separate mapbook) would be a lot easier.

**Comment by brentfraser** [comment]
FYI, we've now included census.gpkg (and the instructions for creating it) in [gm3-demo-data](https://github.com/geomoose/gm3-demo-data/tree/main/demo/census).  It should make configuring GeoServer with data for editing easier

**Comment by brentfraser** [comment]
@klassenjs I guess we could include an mapbook-editing.xml in the standard desktop example.

**Comment by klassenjs** [comment]
It would also be nice if we could include a Dockerfile in gm3-demo-data (or at least a setup script) that would install GeoServer already configured with the demo data (possibly just census.gpkg, maybe more).

**Comment by klassenjs** [comment]
Do we still have the `?mapbook=` parameter that we can switch mapbooks from the URL?

**Comment by brentfraser** [comment]
I don't think so, but it would be nice to have a` ?mapbook=` parameter

**Comment by brentfraser** [comment]
Now that with GM 3 we have a user-edited `app.js`, it should be easy to add that in our desktop example.

**Comment by brentfraser** [comment]
@klassenjs   For now, how about two mapbooks:
- `mapbook.xml` (as it is now)
- `mapbook-editing`: a copy of mapbook.xml with edit layers added.
You could do a `sed` on `app.js` to replace the `mapbook.xml` with `mapbook-editing.xml` on install of the on-line demo?

**Comment by brentfraser** [comment]
My current plan is to have two additional mapbooks in the examples/desktop folder:
```
mapbook-edit-geoserver.xml
mapbook-edit-tinyows.xml
```
They would be a super-set of the current `mapbook.xml` and would contain additional map-sources and layers relevant to each of the two WFS-T servers.  The user could simply change the `app.js` to load the desired mapbook (and of course setup the desired WFS-T server).  This would be described in the documentation.

  This would eliminate duplication of .css etc required if we had a separate examples/editing folder.

**Comment by brentfraser** [comment]
Update to my plan.  After renaming the geoserver mapsources and changing the srs of the mapsources, it looks there are very few differences between `mapbook-edit-geoserver.xml` and `mapbook-edit-tinyows.xml`,  so I may just have one `mapbook-editing.xml` with the TinyOWS config values commented out:

```XML
    <map-source name="census_landmarks-wfst" type="wfs" >
        <url>http://localhost:8080/geoserver/wfs</url>
        <config name="namespace-uri" value="http://geomoose.demo" />

   <!--
        <url>http://localhost/cgi-bin/tinyows.exe</url>
        <config name="namespace-uri" value="http://localhost/cgi-bin/tinyows.exe" />
    -->
```

@jmckenna While this will make maintenance easier, I don't know how this would affect ease-of-packaging a TinyOWS example within MS4W.  Thoughts?

**Comment by klassenjs** [comment]
FYI: The package building scrips are here (and are based on transforming
the npm package (generated with npm pack).

https://github.com/geomoose/gm3-admin

**Comment by jmckenna** [comment]
@brentfraser commented-out sounds like a good plan to me.

**Comment by brentfraser** [comment]
I'm trying to imagine how to minimize the new-user confusion when using MS4W to 
- install GeoMoose (Done, via MS4W)
- install Mapserver+TinyOWS  (Done, via MS4W)
- install/download the GeoMoose Demo/Example editing data (doc, script?)
- load the Editing data into Postgis  (doc, script?)
- configure TinyOWS (script?)
- try out Editing in browser

Maybe just some GeoMoose tutorial doc could do it.

**Comment by jmckenna** [comment]
Regarding MS4W, I'm handling that, don't worry (that's my fulltime job, literally).  I'll be enhancing the installer to also automatically install the new GeoMoose demo etc, as well as the documented steps and scripts (most of which I've already been distributing for TinyOWS+MS4W and testing in PostGIS for each release).  If you can focus on the GeoServer-side of things, I'll tackle the MS4W side :)

**Comment by tchaddad** [comment]
I can also help on the TinyOWS+PostGIS pathway, at least as a tester that feeds into the GM docs...

**Comment by jmckenna** [comment]
Let me know when I can start to add the editing demo...

**Comment by brentfraser** [comment]
I've created PR #671 containing the new mapbook-editing.xml.   My original doc snippet is at  [Editing-Vectors-Using-GeoServer](https://github.com/geomoose/gm3/wiki/Doc-In-Progress:-Editing-Vectors-Using-GeoServer-with-GeoMOOSE), and it should be good enough to show how to load the test data and make it available via GeoServer.  I'm in the process of re-writing it to reflect the new mapbook (and add TinyOWS details).

**Comment by brentfraser** [comment]
Done (I think).
