### ISSUE TITLE
Discussion: Re-organization of Layer tools

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#636]
(This issue is about tools on the layers in the Catalog tab, not the page toolbar or tools on the map.)

**The Problem:**

  The layer tools add visual clutter to the Catalog's layer list.  While the tools add access to functionality, their appearance on every layer (or at least those configured by the admin) can cause cause confusion/anxiety by the user.

**The Solution:**

In keeping with the concepts of information hiding and minimizing chartjunk, I propose we hide the tools in two toolbars: one for "standard" tools, and one for editing tools.

_The current situation:_
Note: because all the tools are enabled in the mapbook (not a common situation), there are lots of them shown, so they "wrap" to fit in the Catalog tab.

![image](https://user-images.githubusercontent.com/1638313/111329285-a0da1400-8634-11eb-8b07-a4a7908f79dd.png)

_The proposed solution:_
In the solution shown below, the Standard toolbar is shown/hidden by clicking on the Layer title, while the Edit toolbar is shown/hidden by clicking on the "edit" icon to the left of the Layer title (if editing is configured in the mapbook).

![image](https://user-images.githubusercontent.com/1638313/111352268-9bd38f80-8649-11eb-84ba-b1d5c697b5b2.png)

Comments appreciated!

**Comment by elil** [comment]
Generally seems to make sense.

The edit icon is very obvious despite the fact that it is the less common
situation.  Would it make sense to swap the function of clicking the layer
for edit and a (different) icon for show tools?  Or keep the edit icon and
use a different indicator for the availability of more tools (bold layer
title, layer title with grey highlight behind it, something else)?

Eli

**Comment by brentfraser** [comment]
@elil Yes displaying the edit icon would be rare, since most installations would not have editing layers.  And we could have an icon to indicate tools-are-available-for-this-layer.  I had that in my original proposal but instead went for a minimalist look.

**Comment by brentfraser** [comment]
At our last PSC meeting Jim had asked about putting the edit icons on the map like the zoom in/out icons (and the edit geometry icons).  Here's a mock up of what that could look like:

![image](https://user-images.githubusercontent.com/1638313/126196456-0581c825-f3d0-4787-8743-0afd8f30cbd4.png)

Note:
- the edit icons are removed from the catalog
- the enable-editing icon is now on the left of the layer title in the catalog

**Comment by elil** [comment]
In this picture, I see that "Census Roads" is the only visible layer.  How do I know that I'm editing that layer and the target of the edit tools is "Census Roads"?  How would this look different if editing "Census Landmarks"?

**Comment by klassenjs** [comment]
@elil maybe we should highlight the layer in the catalog (or at least the editing button)?

Was it intentional that `Drawing and Markup` didn't also get updated?

**Comment by brentfraser** [comment]
@eli yes some kind of highlight of the layer entry (or the enable-editing icon) would be good.
@klassenjs :  sorry about that; I was focusing on the Census layers and ignored the "Drawing and Markup" layer.  but yes the edit tools would work the same for it.

**Comment by tchaddad** [comment]
@brentfraser looks pretty good - couple questions:

- is that first icon on the left in the edit toolbar layer-specific? (meaning you are editing a line layer, and so you only see the line editing icon)?
- how will editing the attributes work? Will the edits happen in a super-tab on the left, or in a table that pops up down below?

**Comment by brentfraser** [comment]
@tchaddad yes the editing icons would be geometry-type (point, line, polygon) specific.  

The edit properties function pops up a modal dialog

![image](https://user-images.githubusercontent.com/1638313/126205354-266b50e3-290e-4369-a9c4-8671c31e9e7e.png)

**Comment by tchaddad** [comment]
Nice, on both counts.

On the topic of showing which layer is currently being edited, maybe an easy solution would be to make the layer name bold, and/or use the same grey highlight that the tool buttons seem to be using...

Another suggestion: on a wider screen I would hope that more space appears between the Zoom tools and the edit tools. That, plus possibly  stack the Zoom icons in a column, so it is clear that they are a different set of functionality.

**Comment by brentfraser** [comment]
Completed in #677
