### ISSUE TITLE
Remove "DUMP TRUE" from all .map files in gm3-demo-data

### ISSUE THREAD

**Issue by jmckenna** [geomoose/gm3#639]
- the upcoming MapServer 8.0 has finally removed the layer's DUMP parameter (it was initially deprecated in the 6.0 release)
- if any mapfiles in the GeoMoose demo reference DUMP, an error will be thrown
- all mentions of DUMP in any mapfile in the gm3-demo-data package must be removed (LAYER METADATA should be used instead)
- (I could not find a way to file a ticket in the gm3-demo-data repository)
- the current MapServer source as of now will throw this error, so I believe the gm3-demo-data package should be updated as soon as possible

**Comment by theduckylittle** [comment]
Merged!
