### ISSUE TITLE
Add a mapbook hash parameter 

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#645]
To allow switching of mapbook via URL ([#631](https://github.com/geomoose/gm3/issues/631#issuecomment-800395285)).  Especially helpful for easily creating our on-line demo.

**Comment by theduckylittle** [comment]
I tried to do this in the hash but there were issues conflicting with the hash tracker. Instead of completely rewriting that logic I took a cop-out and switched to using a query parameter.
