### ISSUE TITLE
Inconsistency on "results header" configuration in app.js

### ISSUE THREAD

**Issue by robinrullo** [geomoose/gm3#655]
I tested some configurations and noticed that there's an inconsistency on the documentation and app.js and missing documentation.

The doc says that only services options can be used to configure the info header but on demo app.js, in the GM3 Application options, there is a configuration for the results header too, not used or not used yet, and keys doesn't correspond with the service configuration.

```javascript
results: {
    enableBufferAll: true,
    showLayerCount: false,
}
```

I think that the purpose was to allow to configure the services globally from there ?

So I think that the config props (which already is DEFAULT_CONFIG with the GM3 Application options merged) should be used on the service manager. (And move these lines to DEFAULT_CONFIG)

```diff
const resultsConfig = {
-   showFeatureCount: true,
-   showLayerCount: true,
-   showBufferAll: false,
-   showZoomToAll: true,
+   ...this.props.config,
    ...service.resultsConfig,
};
```
Or was it for something else?

**Comment by theduckylittle** [comment]
Good catches. These were definitely some cruft missed during the origin PR's review. I did a follow up that removes the code from the demo, mixes in the global config, and properly puts the defaults somewhere sane.
