### ISSUE TITLE
Special characters not correctly sorted in the Grid

### ISSUE THREAD

**Issue by robinrullo** [geomoose/gm3#663]
Values in the Grid are not sorted correctly when words begin with special characters. Currently, special characters are sorted after **Z** (in javascript, compare `'É' > 'Z' = 1`). But **É** should be between **D** and **F**.
And also in Swedish, **Ä** is after **Z** but in French is before **B**.
So [`Intl.Collator().compare(a, b)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/compare) can be used in this case and use the browser locales.
```diff
sortResults(results) {
    const sorted_results = [].concat(results);

    const sort_col = this.state.sortBy;
    const sort_asc = this.state.sortAsc;
    const sort_as = this.state.sortAs;

+   const collator = Intl.Collator();
    sorted_results.sort(function(a, b) {
        let value_a = a.properties[sort_col];
        let value_b = b.properties[sort_col];
        if(sort_as === 'number') {
            value_a = parseFloat(value_a);
            value_b = parseFloat(value_b);
        }
        if(sort_asc) {
-           return (value_a > value_b) ? 1 : -1;
+           return collator.compare(value_a, value_b);
        }
-       return (value_a > value_b) ? -1 : 1;
+       return collator.compare(value_b, value_a);
    });
    return sorted_results;
}
```

**Comment by elil** [comment]
See also #378
