### ISSUE TITLE
Hash Track + Opacity?

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/gm3#68]
Not sure if this is strictly necessary but opacity for a map-source can now change.  It may be worthwhile to track it.

**Comment by klassenjs** [comment]
I had expanded the scope of #66 earlier, but didn't chamge the title.  I think we need to make a clear choice of what we track to balance the goals of restoring a previous map view as it was and staying within a reasonable character count.

**Comment by theduckylittle** [comment]
Considering this a dupe of #66  and closing.
