### ISSUE TITLE
Grid templates only render for services titled 'select' and 'search'

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#684]
The current templates in the search/select/identify javascript are `search-grid-row` and `search-grid-columns` (interchanging search with select or identify). When using these templates, the grid only renders if the service is titled search, select, or identify. 

For example, the instructions at https://docs.geomoose.org/3.x/howto/add-grid-to-search-and-identify.html are sufficient for adding a grid to the Search Parcels tool, but not the single field search tool.

For the latter, you would also need to add `single-search-grid-row` and `single-search-grid-columns` templates to `search.js`, and add those corresponding templates to the map-source.

My intuition when looking at the documentation was that you'd be able to reference the same `search-grid-row` and `search-grid-columns` templates in different search tools like you could with gridRow or gridColumns (or perhaps even use the formula of `[service name]-grid-row` and `[service-name]-grid-columns`).

This isn't a major issue as you could just modify the service javascript files to add templates, but I thought I'd add it as an issue as I wasn't sure of the intended behavior.

**Comment by theduckylittle** [comment]
Hm... the code seems to be using the service name for finding the templates:
 - https://github.com/geomoose/gm3/blob/main/src/gm3/components/grid.js#L556

Can you include an `app.js` and mapbook XML snippet demonstrating the bug?

**Comment by chughes-lincoln** [comment]
I think the reason this doesn't occur in the demo is that there's only one select tool, and the grid isn't set up for any of the search tools (that specifically have service names other than search).

Setting the search grid in the map-source in the mapbook.xml:
```
    <map-source name="Taxlots-wfs" type="mapserver-wfs">
          <file>a_assessment.map</file>
          <param name="typename" value="ms:Taxlots" />
          <!-- set pixel-tolerance to 0 so identifications don't grab adjacent results -->
          <config name="pixel-tolerance" value="0"/>
          <layer name="Taxlots_selection" selectable="true" title="Taxlots">
            <template name="search" src="./templates/search_taxlots.html" />
            <template name="select" src="./templates/select_taxlots.html" />
            <template name="identify" src="./templates/identify_taxlots.html" />

            <template name="search-grid-columns" src="./templates/taxlot-columns.json" />
            <template name="search-grid-row" src="./templates/taxlot-row.html" />

           </layer>
    </map-source>
```
And the service code in the toolbar of mapbook.xml:
```
        <drawer name="searches" title="Search">
            <tool name="search-Taxlots-simple" title = "Simple Taxlot Search" type = "service"/>
            <tool name="search-Taxlots" title= "Advanced Taxlot Search" type = "service"/>
            <tool name="search-Surveys" title= "Advanced Surveys Search" type = "service"/>
        </drawer>
```

Referencing that service in App.js:
```
        app.registerService('search-Taxlots-simple', SearchService, {
            // The input fields are defined only using one field
            title: 'Simple Taxlot Search',
            resultsTitle: 'Taxlots Search Results',
         
... Additional code to program a single search ...

            zoomToResults: true,
            gridMinimized: true,
            results: {
              showBufferAll: true,
              showLayerCount: false
            }
        });
```

With the above code the grid doesn't render when running a single search. If I change the service name to `search` and reference that search service in the toolbar, then the grid does render. If I keep the service name `search-Taxlots-simple`, but also add
```
            templates.push('@search-Taxlots-simple-grid-columns');
            templates.push('@search-Taxlots-simple-grid-row');
```
in the search.js file, while changing the template names in the mapbook.xml to `search-Taxlots-simple-grid-columns` and `search-Taxlots-simple-grid-row`, the grid also renders.

**Comment by theduckylittle** [comment]
Found the bug for this. There is now two different ways to handle this.

1. With the updated services it should work to do this in the mapbook:
```
+            <template name="single-search-grid-columns" src="./templates/parcel-columns.json" />
+            <template name="single-search-grid-row" src="./templates/parcel-row.html" />
```
2. Now, settings `alias` on the service will properly re-use templates from another service. In this case, it is handy to use the `search` templates: See the updated doc in #767

**Comment by chughes-lincoln** [comment]
Tested both these options and the grid generates correctly.
