### ISSUE TITLE
Navigation Tools on Toolbar - Zoom In

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#689]
In GeoMoose 2 there were a few more tools on the toolbar for navigating around the map, mainly the ability to use the Zoom In tool to either zoom in a set amount by clicking on the map, or zoom in to a box by drawing a box (as well as a Zoom Out tool that does the opposite and a Pan tool that essentially turns off the other tools and switches back to Panning).

I think adding in the Zoom In tool would make navigating the map easier for the average user. You can still zoom to a box by holding shift while drawing a box, but most users won't know about that shortcut, and using the scrollbar to zoom in quickly to the location that you want isn't as easy if you're on a laptop without a mouse and don't have an easy-to-use scrollbar.

**Comment by theduckylittle** [comment]
I'm sympathetic to this request, especially for users/administrators who are looking to lateral over from a desktop application that offers those zoom tools. I've spent some time looking into this and have found a few things that give me pause:
1. The number of tickets we've spent on changing interactions with the map. There is a lot going one when changing services, selection controls, and drawing. Right now, the zoom tools are ever present. That means we don't have an easy code path inside of the map component to change that.
2. OpenLayers doesn't offer a built-in interaction for doing this: https://openlayers.org/en/latest/apidoc/module-ol_interaction.html -- Not that we don't work around that all the time but it adds another difficulty.
