### ISSUE TITLE
Zoom to a Point causes Singularity

### ISSUE THREAD

**Issue by tchaddad** [geomoose/gm3#719]
Saw this in someone else's site - can't reproduce in demo because we don't have a searchable point layer.

- User does a search on a point layer (e.g. water meters)
- selects zoom to from search results
- Zooms to the location at the atomic level

relates to https://github.com/geomoose/gm3/issues/349 and https://github.com/geomoose/gm3/pull/355

**Comment by klassenjs** [comment]
We have a parcel points layer so we could make that searchable.

**Comment by chughes-lincoln** [comment]
I noticed this on my site as well. As a minor workaround you can set the max scale in app.js.

**Comment by tchaddad** [comment]
Thanks, I see this was already discussed in https://github.com/geomoose/gm3/issues/583 so will use that for now
