### ISSUE TITLE
Setup Browserslist in package.json

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#723]
Currently the build system produces the following warnings:

```
[Browserslist] Could not parse /home/jimk/Public/GeoMoose/package.json. Ignoring it.
[Browserslist] Could not parse /home/jimk/Public/GeoMoose/package.json. Ignoring it.
```

It looks like babel and webpack use this list to trim polyfills that are unnecessary for the supported browsers.  Although this appears to make very little difference in output code size.  However, it seems like this might be a good way to state our supported browsers in a standardized computer readable form.

I was thinking something like:

```
  "browserslist": [
    "defaults",
    "not ie <= 11"
  ]
```

although we may want to restrict more tightly.

**Comment by theduckylittle** [comment]
Included in the latest audit updates:
 - https://github.com/geomoose/gm3/pull/733
