### ISSUE TITLE
Filter - Multiple Filters in Single Table

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#736]
Trying to filter multiple fields in a single table fails. It seems to just filter whichever field you've filtered most recently. This is (at least) using the filter type 'list'.

i.e. if I have a parcel dataset that has dimensions for length and width in separate columns, I can't filter where length _and_ width are greater than a certain size.

**Comment by theduckylittle** [comment]
I believe https://github.com/geomoose/gm3/pull/766 will satisfy this. While that example uses `ilike` and `eq` it would be equally possible to add `gt` and `lt`

**Comment by chughes-lincoln** [comment]
Fixed by https://github.com/geomoose/gm3/pull/785. Also really liking how the filters behave now, particularly with the select none/all.
