### ISSUE TITLE
Search Parcels doesn't highlight results

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#737]
Results in map don't highlight immediately after search or on hover over the results.

**Comment by chughes-lincoln** [comment]
It seems like the default option is inconsistent. For the demo, I don't see anything in the mapbook for setting whether highlight is true or false for parcels, but it highlights results for select but not search or identify. On my build, if I don't set any highlight parameters, it highlights for search, but not select or identify. Though for some reason results are highlighted for search even if I set highlight="false".

It might be a good idea to have the highlight default be set to true. It would probably be more useful to new users to have everything highlight and be able to turn it off than the other way around.
