### ISSUE TITLE
Sketch - Can't (easily) select transparent polygons

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#752]
When you create a polygon you can adjust the fill opacity to make it fully transparent. If you do this you can't easily go back and select this polygon to edit the geometry or attributes. You actually can select the polygon by clicking on the outline, but it no longer recognizes the interior as part of the polygon, so just clicking in the middle of the shape doesn't select it.

**Comment by klassenjs** [comment]
I'm not sure how I feel about this.  

Part of me thinks that clicking on nothing (like the interior of a polygon with no fill) is expected to select nothing.  Part of me thinks it is unusual to set a polygon to no-fill by setting the fill opacity to 0 instead of having a separate control for that.

**Comment by chughes-lincoln** [comment]
My main concern is that I think users will want to add sketches without a fill so that you can easily see what's underneath, and will assume that it's a bug that they can no longer click on the interior.

**Comment by theduckylittle** [comment]
The I've handled this, historically, is to only allow the minimum transparency to be .01-.05 transparency. 

It would be a small tweak to the mapbook to do that. Thoughts?

**Comment by elil** [comment]
For people doing the transparent line/poly/point for the label only it might be inconvenient.  Or perhaps .01-.05 transparency is not noticeable unless you're looking for it.
________________________________

**Comment by chughes-lincoln** [comment]
This issue also occurs if you set the highlight fill for results to be transparent (you then can't do anything that requires clicking on results like measuring or buffering results). I handled that by setting the highlight fill to be 0.00001 transparency (perhaps overkill, but it appears transparent to the user).

**Comment by klassenjs** [comment]
I still think we need to support both behaviors or large polygons can block the selection of smaller features when zoomed in.  Just pushing the min-transparency to not-quite zero is going to break other things.  I'd really like a good universal answer to this, but I don't have one at the moment.

**Comment by theduckylittle** [comment]
I'm not saying we don't support both behaviours. The styles are completely customizable by the user, but I would expect that if I *draw* something on the map and even if it *looks* transparent that I can click on it. 

For out-of-the-box behaviour I feel the .01 opacity is a reasonable compromise.

Users could still adjust it if they want true transparency and the vector layers can still be styled however they want (see @chughes-lincoln 's .0000000000000000000000000000000 -breathes- 0000000000001 hack above).

**Comment by theduckylittle** [comment]
And this discussion is in the scope of the Sketch layer, none of the others would be directly effected.

**Comment by klassenjs** [comment]
What happens if step is set to 0.099?

Or to minimize round off issues with repeating "decimals" in binary:
set min to   0.00878906250  (.00000010010)
and step to 0.09912109375  (.00011001011)
?

**Comment by klassenjs** [comment]
Or for that matter, let the slider hit 0, but set a minimum in whatever function actually applies the value to the style.

**Comment by chughes-lincoln** [comment]
0.099 also works.

**Comment by chughes-lincoln** [comment]
Returning back to this, for my site I set the min opacity to 0.00001 and the max opacity to 1.00001 which works well. The transparency slider works, and sketches are selectable. Setting min to 0.00001 and max to 1, with a step of 0.099999 would probably give the same result (and may prevent any issues that could arise from setting a max opacity greater than 1 - though I haven't seen any so far).

**Comment by chughes-lincoln** [comment]
Closing as adjusting the min/max opacity and the step works.
