### ISSUE TITLE
Documentation - RoadMap

### ISSUE THREAD

**Issue by Gonzant** [geomoose/gm3#759]
Hello, is a RoadMap for futures version available? I find this https://github.com/geomoose/gm3/wiki/Roadmap but its outdated.

I need to implement a time widget and I want to know if it is in your roadmap?
If not, I would be pleased to develop it.

**Comment by tchaddad** [comment]
hi @Gonzant , I don't know if there is a more recent roadmap (probably we should create one), but there has been some interest in support for a time-slider mentioned in some of the PSC meeting minutes from earlier this year:

https://github.com/geomoose/geomoose/wiki/PSC-Meeting-2022-04-15#missing-features-discussion

Maybe @klassenjs or @theduckylittle can say more about if any moves have happened in this direction behind the scenes.

Most likely many folks would be interested in hearing more about what you have in mind!

**Comment by klassenjs** [comment]
Interested, but haven't had a chance to do anything about it yet.

**Comment by klassenjs** [comment]
The best roadmap right now is in the PSC meeting minutes for future ideas/goals and looking at the upcoming milestones in GitHub for things actually in progress.

**Comment by Gonzant** [comment]
Thanks for the responses, and for the work you have been doing in this project!

Probably, I will develop this new feature and make a pr when I finish it.
