### ISSUE TITLE
Measure multiple features from results

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#780]
Measure -> Feature From Results -> Select multiple results from the results layer (shift click)

What happens: only the first feature is measured
What was expected: features summed (or block multi-select).  

It would be kinda cool to get the area of multiple parcels though (select/measure multiple parcels with the same owner, etc.).  I have no idea what happens if someone selects a polygon and a line from a result set.  My guess is only allowing one selection at a time would be the best bet.

**Comment by chughes-lincoln** [comment]
Looks to be the same as https://github.com/geomoose/gm3/issues/703

**Comment by klassenjs** [comment]
Duplicate
