### ISSUE TITLE
Select - AutoGo's after first selection

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#788]
If you do a select on the demo, you need to click Go or hit Enter on your keyboard to run it. On subsequent selections the tool runs when you double click to finish the geometry, without clicking Go (i.e. it doesn't bring you back to the select tool where you can change the select dataset/the Using parameter/buffer distances etc...)

Not sure how much of an issue this is, but it's a change in behavior so I thought I'd mention it (the editing demo which is still on 3.8 behaves like it used to).

**Comment by theduckylittle** [comment]
#800 address this behavior (it's fixed) but introduced #804 .
