### ISSUE TITLE
Select Fails Without Default Layer

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#793]
Similar to the identify/select bug mentioned here: https://github.com/geomoose/gm3/pull/762

If you don't have a default layer set, you need to choose something else in the select dropdown menu in order for the tool to run.
Not setting a default layer allows the tool to default to whatever is on top of your map, which can be useful (at least in Edge/Chrome).

**Comment by theduckylittle** [comment]
I'm not sure I understand the bug or feature request.

- https://github.com/geomoose/gm3/pull/786 - fixes the issue where the default is not specified, the first layer in the list should be selected by default.

**Comment by chughes-lincoln** [comment]
I must have been testing this on the wrong PR or before that was incorporated. Works now.

**Comment by chughes-lincoln** [comment]
Actually believe this was fixed by https://github.com/geomoose/gm3/pull/795
