### ISSUE TITLE
Measure no longer chooses a default

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#796]
Previously if you started the measure tool, Draw Line would be selected by default, allowing the user to measure without choosing any options.

On the demo beta none of the radio buttons are selected when you start measure. Not a major issue, but I think that it helps the user to be able to see all the options that are available.

**Comment by theduckylittle** [comment]
https://github.com/geomoose/gm3/pull/799

**Comment by chughes-lincoln** [comment]
Fixed by https://github.com/geomoose/gm3/pull/799
