### ISSUE TITLE
Buffer - Service State Issue

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#809]
If you buffer results and then try to do a buffer around the results of the buffer, it uses buffers the previous feature in addition to the new one.

i.e. if you select Parcel A and do a buffer around it, you get Parcels A, B, and C in your results. If you then try to do a buffer around Parcel C, it does a buffer around Parcels A and C instead of just Parcel C.

**Comment by theduckylittle** [comment]
I'm not seeing this bug on the main branch.
- Start the select tool
- I used various selection techniques.
- Using "Buffer Selection" appears to buffer the results
- If I then use the select tool again and select a feature from results it buffers the feature I selected.

Can I get some screenshots or a slightly more detailed scenario? I may be just losing something in translation.

**Comment by chughes-lincoln** [comment]
Your last bullet point (I think) is the discrepancy. You're going back into the select tool to click a feature on the map from your results and buffer that feature. I'm going into the grid results and buffering the feature from there which isn't clearing out the previous selection/buffer.



- Select the SW parcel in the demo dataset (I just used draw polygon). 
- From the results, do a 2 mile buffer and click Go.
- From the results again, click buffer feature for a separate result
  - At this point if you don't change the buffer distance it's showing the previous 2 mile buffer + a 0 distance buffer for the new feature
- If you update the With Buffer units it calculates that buffer using the first buffer feature and the new one.

![image](https://user-images.githubusercontent.com/43766648/234330513-e08b0c26-a1ed-4519-bd6c-e9ea69b4a791.png)

**Comment by chughes-lincoln** [comment]
Fixed by https://github.com/geomoose/gm3/pull/882
