### ISSUE TITLE
Print - Image in Template - i.e. north arrows/organization logo

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#810]
Adding an image in a print template (https://docs.geomoose.org/3.x/howto/print-layouts.html?highlight=print) no longer works (at least I haven't figured out how to get it working). Previously you could convert your image to a base64 string and reference it in the image_data parameter. On 3.10.0 you can also just directly reference a png.

**Comment by theduckylittle** [comment]
Ack! The new lint fixes got a little aggressive. New MR handles it properly.

**Comment by chughes-lincoln** [comment]
Fixed by https://github.com/geomoose/gm3/pull/827
