### ISSUE TITLE
Catalog/Toolbar/Map won't load if user has a layer favorited that no longer exists

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#812]
If a user favorites a layer and then the admin removes that layer, the Catalog/Toolbar/Map won't load and site will throw a 'cannot read properties of undefined layer at mapsource/favorite'. If the user then clears their cookies the site will load properly. This doesn't appear to be an issue in 3.10.

This isn't a massive issue as there's an easy fix for it, but users wouldn't necessarily know that they need to clear their cookies, and it restricts the admin from making changes to any map-source as it could make their site appear very broken to certain users.

**Comment by klassenjs** [comment]
Good find.

**Comment by chughes-lincoln** [comment]
Fixed by https://github.com/geomoose/gm3/pull/815
