### ISSUE TITLE
Clicking the select tool highlights identify results

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#818]
If you have identify highlight set to false for a layer, and select highlight set to true, clicking the select tool after an identification highlights all previous results (assuming you didn't clear your results after the identify)

i.e. Turn on pipelines in the demo. Identify a pipeline which doesn't highlight the result because it's set to false. Click Select and the pipeline highlights before you do a selection.

**Comment by theduckylittle** [comment]
Is this a bug or a feature? 

For example, wanting to buffer the feature you just identified?

**Comment by elil** [comment]
This appears to also impact search (identify then search) which is certainly not a feature :)

I'm wondering about stop-gap measures like invoking a clear results in the beginning of search, select, etc.  Hmm, that would also clear results from search or select results that are intended.

**Comment by chughes-lincoln** [comment]
This also impacts measure (identify then measure).

**Comment by theduckylittle** [comment]
This was fixed in #879
