### ISSUE TITLE
Select Features by "Draw Multi-Point" does not draw or select

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#82]
Trying to draw and use a Multi-Point for Select Features does not work.  It does not draw any points, it does not activate the "End Drawing" option, and it does not select anything.

**Comment by theduckylittle** [comment]
Found the bug, I had a typo while handling the multipoint handler.  When #88  is merged this should work itself out.

**Comment by elil** [comment]
This does now work as expected for multipoint select (and thus could probably be closed).  As noted in #88, there are still issues with multipoint buffer.
