### ISSUE TITLE
URL Tracker - Bbox format doesn't exactly track the location anymore

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#823]
If you change the location format to bbox in app.js, refreshing the browser or sharing the url with the bookmark tool results in a map that's slightly zoomed out. (i.e. on the demo, change the tracker format to bbox. If you zoom to parcel boundaries via the zoom to extent tool, you can then continually refresh the browser to see it's slightly zooming out each time).

**Comment by theduckylittle** [comment]
Found the bug! It was because we pad the call to `zoomToExtent` this now lets the tracker _not_ pad that bounding box.

**Comment by chughes-lincoln** [comment]
Fixed by https://github.com/geomoose/gm3/pull/825
