### ISSUE TITLE
+/- Zoom Buttons zoom to whole world

### ISSUE THREAD

**Issue by klassenjs** [geomoose/gm3#828]
This might be related to using bbox on the hashtracker.  I haven't really tracked this down yet, but noticed it when testing the zoom creep pr.

**Comment by theduckylittle** [comment]
This is a regression due to how we handle zoom-by-zoom and zoom-by-resolution. I'm digging in now.

**Comment by chughes-lincoln** [comment]
Not sure if there were any particular steps needed to replicate this, but I rebuilt on the demo, tested the default xyz, lonlat, and bbox and didn't see any issues.
