### ISSUE TITLE
Select Features defaults to all geometries 

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#83]
Instead of making a drawing or selecting a drawing in the drawing phase of Select Features, just hit, "Go."  This selects all the features.  This happens with all drawing options.  It should probably select none and give some message that "Nothing matched your selection criteria" or "No results" some other useful message.

**Comment by klassenjs** [comment]
I agree (although this is kind of a cool way to get the whole list in the grid, it isn't what I'd expect and it locks up the browser for awhile.  We should make it harder for end users to hurt themselves, if they really want to select everything, it is easy enough to make a big polygon.)

**Comment by klassenjs** [comment]
@elil Please review.

**Comment by elil** [comment]
No longer selects everything and gives a meaningful message.
