### ISSUE TITLE
Start Service from URL - Add catch error for incorrect field name

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#830]
Currently you can do a search from a URL - see the last example at https://docs.geomoose.org/3.x/howto/start-a-service.html

Right now if someone has the incorrect service name a console error will be thrown and nothing will happen. If someone has the correct service name but an incorrect field name the service will spin forever until the tab crashes.

I don't know how feasible this would be, but it would be a nice enhancement if there was some sort of error catcher for incorrect field names as well as service names (mainly to avoid people trying to guess field names and complaining about the site crashing).

**Comment by theduckylittle** [comment]
This seems to be failing gracefully with main. We'll need to check for updated scenarios at a later date.
