### ISSUE TITLE
Select Features using "Select from Drawing and Markup" allows for selectiong mutiple drawings but only uses the last one

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#84]
Make various drawings and markup.

Select Features... "Select from Drawing and Markup," press and hold shift key, click and select multiple drawings, hit go.  The selection returned in based only on the last selected drawing.  Selections can also be of multiple geometries types (may be fine but may need to take that into account).  

Selection should either be for all selected drawings or selection should not allow multiple selections or there should be an error message to only use one selection.  

Measure and other aspects are probably a separate issue, or maybe this issue here should be a sub-issue of the general issue of handling multiple drawing selections.  In measure, a user can select two drawings and it does not sum their area (also, the user is not prevented from selecting different geometry types).

**Comment by klassenjs** [comment]
Cool, I had no idea shift key would allow multiple selections.

**Comment by klassenjs** [comment]
@elil Please Review.

As I said in the PR, I could see multi-select being a future enhancement, but since this isn't a regression from 2.x and in the short term I'd rather have a stable 3.0.0 release rather than waiting to solve the hard problem of how to make the tools multi-geometry aware.

**Comment by elil** [comment]
Is #122 supposed to be in the demo now?  I can still select multiple geometries.

**Comment by klassenjs** [comment]
The demo works for me. I see it at cfcb073 which includes this fix.

Try clearing browser cache.  I have found sometimes it doesn't pickup on the new geomoose.min.js.
