### ISSUE TITLE
Expand Measure to point (coordinate)

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#85]
The Measure tools only measures lines (direction and length) and polygons (areas).  Measuring a point could return a coordinate.  

As a related aspect to this, Measure... Select From Drawing and Markup, (click a single point), gives no result.

**Comment by theduckylittle** [comment]
Is it the latter issue that makes the former necessary? Which coordinates should be shown? Should there just be a message that says, "Points don't measure, yo"? So the functionality doesn't look broken?

**Comment by klassenjs** [comment]
I think the getting a coordinate off the map is useful.   Right now I tend to just hover over and use the coordinate display at the bottom, but that is hard to copy/paste and also hard to switch windows without it changing.

So having a way to pick a point and have it stick would be nice.  I am not sure if the measure tool is the obvious place for it.

Which coordinates?  Same ones configured for the bottom coordinate display.

**Comment by klassenjs** [comment]
This also is leading towards the search coordinate tool I want (as a panto/zoomto was my initial thought but or adding a point to a layer might be nice too).

**Comment by elil** [comment]
No, the latter issue is not necessitating the former.  The latter issue (Measure...select from...point...no result) is a bug and should be fixed.  It could be fixed by either doing something (the former) or giving a message or preventing the attempt. 

The former issue (It would be nice to "measure" points that return a coordinate) is an enhancement and can be addressed however enhancements are handled.

**Comment by klassenjs** [comment]
@elil Please review.

**Comment by elil** [comment]
The bug (measure...select point drawing...no result) is fixed.  And the enhancement to measure a coordinate directly or by selecting an existing drawing point is now present.
