### ISSUE TITLE
[docs] missing favicon

### ISSUE THREAD

**Issue by jmckenna** [geomoose/gm3#860]
- usually set in Sphinx's [conf.py](https://github.com/MapServer/MapServer-documentation/blob/main/conf.py#L153)

  `html_favicon = "_static/mapserver.ico"`
  
  
![favicon](https://github.com/geomoose/gm3/assets/1611709/5ce6b814-09cc-4b1e-8b1a-ecd4aacd5e10)

**Comment by jmckenna** [comment]
(initially filed in [geomoose-website](https://github.com/geomoose/geomoose-website/issues/19) - I forget which repo to use)

**Comment by tchaddad** [comment]
@klassenjs:  the favicons are here:
https://github.com/geomoose/geomoose-art/tree/main/logo_2011/favicon

**Comment by klassenjs** [comment]
Let the moose roam free amongst the tabs.
