### ISSUE TITLE
Identify can hang on Measure input

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#87]
Click Identify (don't click anything else here), click Measure, select Draw Line, draw a line, click Identify.  Identify tab is no longer functional.

**Comment by theduckylittle** [comment]
Found the issue,  the servicemanager was treating the measure tool as *too much* of a special case.  This has been quieted down now.

**Comment by elil** [comment]
Tested and looks to work.  (Are we still doing reporter closes issue?)
