### ISSUE TITLE
HashTrack and "Built-in" Layers

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/gm3#89]
Two different types of "smart" layers have been added to the application:
1. "results/*" there are two different results layers.  One for display the results of a query (and honouring the client side filters for it) and one for hovering over the results in order to see a 'selected' geometry on the map.
2. "selection/selection" While writing the buffer tool it was important to preview what the user was going to get when they selected applied a buffer. This required having two "seleciton" layers. The first selection layer is built-in to the OpenLayers map and is a consistent target for the OpenLayer's controls to use. the second selection layer is the map-source "selection" with the layer "selection" which is managed by the map to preview the actual selection features as the user gets them.  This is added with PR #88 .

However, when a user decides to remove "results/" or "selection/" layers from the hash then when the services render they can be missing those layers and not see the highlighted results or the selection preview.  i have a couple of thoughts on this:

1. The layers could be forced on anytime they get new data or something is expecting them to be visible.
   This seems like a reasonable "hack" but I do feel like these layers can ALWAYS be on and it will not effect the user experience with how OpenLayers now handles vector layers (that is OL3+ vectorizes them).
2. Add a new "hide from tracking" or "alwaysOn" status for the layers.  
   I actually feel this is a reasonable thing to do.  Some layers are internal, they should always be on and they're lynch pins for good functionality.  
3. Put these layers BACK into the Mapbook and let users add them to the catalog.
   This certainly is an approach and offers a lot of flexibility.  There could even be some CONFIG variables used to set these with reasonable global states and everything.   *BUT* I honestly believe there were some times where we really put effort into maximum flexibility on features and lost consistency from a user's perspective.  Yes, a savvy administrator had more tricks available to them but we had a harder time managing state and in the new version I think we'd have a more difficult time doing testing.  The corner cases start growing out of control.

**Comment by theduckylittle** [comment]
I'd like to implement option 2.

**Comment by klassenjs** [comment]
+1 for Option 2.  I like the flags approach, maybe with the option for more fine grained flags in the future.

**Comment by elil** [comment]
I agree with above, point 3. flexibility and consistency.  Flexibility is very powerful and something that makes GeoMoose fairly unique.  It is also something that complicates our testing and expands our corner cases and can lead to whack a mole.  I'm not sure of the balance to strike.  One complex way would be a mapbook validation tool that identifies conflicting mapbook configurations. But then we would need to write rules for valid mapbook configuration.  

Also, #95, about hovering might more properly belong here.

**Comment by klassenjs** [comment]
Marking this a bug because it is easy to hurt yourself in the current state.

**Comment by theduckylittle** [comment]
Two things:
1. My bad on the syntax, it should be:
```
 <param name="always-on" value="true"/>
```

2. I've now added `parseBoolean` as "true" coming in from the mapbook would bring in a string instead of an actual boolean value.

**Comment by klassenjs** [comment]
Update: <param> conflicted with WMS parameters.  Changed to use options instead of param so there no mapbook syntax at the moment.

**Comment by klassenjs** [comment]
@theduckylittle It's your issue to close.
