### ISSUE TITLE
Add a Length Input Type

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/gm3#9]
GeoMOOSE 2.X had a special type of service input that would allow a user to specify a distance in their preferred units.  gm3 needs the same capability.

Acceptance criteria:
1. A new input type that displays both a text field for the distance and a drop down for units.
2. The new class should be placed in src/gm3/components/selectInputs/length.jsx and appropriately extend TextSelect.
3. gm3/util.js should get a distance conversion function that takes in a length, a source units and a destination units.  There are already functions that convert to/from meters.  Those functions can stay there for now but we should have a new one that follows this prototype: `export function convertLength(length, srcUnits, destUnits)` where srcUnits/destUnits are one of `m,in,ft,mi,km,yd`.  

This is the old 2.X implementation:
 - The input: https://github.com/geomoose/geomoose-js/blob/master/geomoose/GeoMOOSE/ServiceInputTypes.js#L598
- The conversion function: https://github.com/geomoose/geomoose-js/blob/master/geomoose/geomoose.js#L808

**Comment by elil** [comment]
Chains might be useful too.  In 2.#, I think we're using [OpenLayers](https://github.com/openlayers/ol2/blob/f4a4090814f240414548e8eda55070d16f3d3901/lib/OpenLayers/Util.js#L1057).

**Comment by theduckylittle** [comment]
In 2.x we were using the OpenLayer's lookup tables.  If someone has time to submit an addition for chains then it's cool with me.

**Comment by elil** [comment]
:thumbsup: Thanks!

**Comment by theduckylittle** [comment]
I've merged in @klassenjs 's works but that *does not* complete the ticket.  The Input-length type will still be needed. This does give a great example on the proper units conversion. Thanks again!
