### ISSUE TITLE
Activate focus of search box when search icon is clicked

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#94]
If you click the Search Parcels icon and blindly start typing the text does not go in the search box.  It would be better if that text went into the box.  If there were more than one box, it could perhaps be configurable which box was the default (although ideally search would be effective enough that only one box is needed).  

Related, #61 since a common use would be to click Search Parcels, blindly type your search without clicking in any boxes, hit enter, see results.

**Comment by klassenjs** [comment]
@elil Please Review.

**Comment by elil** [comment]
Yes, this works and combined with #61 now eliminates lots of intermediate clicking.  

(I think that there is a lot more clicking to get rid of but that is a separate matter.)
