### ISSUE TITLE
Grid results and tab results behave differently

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#95]
Hovering over grid results highlights that particular parcel in the selection.  Hovering or click on results in the super tab does not do this.  It would be better if the grid and tab behaved in a similar manner.  

Hover could perhaps also be clicking instead.

**Comment by klassenjs** [comment]
I think this is up to how the admin configures the layer in the mapbook.  (Not that the demo couldn't be configured better.)

In the demo the results tab feels kind of redundant to the grid as currently configured.

**Comment by elil** [comment]
Yes, let's configure the demo well to get people off to a good start.  

I'd like the results and grid to match and be synchronized.  Click/Hover/Select in either the results or grid and both it and the other gets highlighted in red.  The feature on the map is already nicely doing this (only from grid).  

Another approach could be that when grid is maximized, the results tab only shows the highlighted result.  

#124 might help this some too.

**Comment by theduckylittle** [comment]
@elil - I've done some improvements. Good enough for 3.0.0? Got any more suggestions?

**Comment by elil** [comment]
I like the summary information!

Is there a scenario in which the layers will be a number other than 1 (for
select)? (I see Identify which does multiple layers uses the same thing and
makes sense).

This could work for 3.0.0.  I'd like to see the tab have identify-like
template information for the individually selected/highlighted grid row.
That way the white space does something productive.  It might just be me
favoring the familiar too...

**Comment by chughes-lincoln** [comment]
I was able to add the ability to highlight tab results while hovering over them. All you need to do is modify the relevant section in the search template with the highlight section of the parcel-row.html
See where I've made the modifications followed by the entire modified template: https://github.com/geomoose/gm3/blob/master/examples/desktop/mapbook.xml#L74

`<template name="search"><![CDATA[
                <div class="search-result"
                  onmouseenter="app.highlightFeatures({'PIN' : '{{ properties.PIN }}'}, true)"
                  onmouseleave="app.clearHighlight()"
                  >
                    <div class="search-label">
                        {{ properties.OWNER_NAME }}
                    </div>
                    <div class="search-action">
                        <div style="padding: 2px">
                            <a onClick="app.zoomToExtent([{{ properties.boundedBy | join }}])" class="zoomto-link">
                                <i class="fa fa-search"></i>
                                {{ properties.PIN }}
                            </a>
                        </div>
                    </div>
                    <div class="search-address">
                        {{ properties.OWN_ADD_L1 }}<br/>
                        {{ properties.OWN_ADD_L3 }}<br/>
                    </div>
                </div>
            ]]></template>`

**Comment by theduckylittle** [comment]
Moving the goal post here to 3.4.0 to discuss if we want to add the above code into the template or write up a doc.

**Comment by tchaddad** [comment]
Sounds like this one is ready / could be considered for the current push?

**Comment by chughes-lincoln** [comment]
I think either adding it to the template or adding a doc would be sufficient. I'd lean toward adding it into the template as I don't see much of a con about being able to highlight the tab results. I've also added a line in between results to make it easier to differentiate between results

**Comment by theduckylittle** [comment]
PR'd, I believe I caught the changes appropriately.
