### ISSUE TITLE
Using Measure after Identify accepts point input but does not return a result

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#97]
Use Identify to click a few points.
Switch to measure. (notice that Draw Line, Draw Polygon, and Select from are not engaged)
Click around the map and points are registered.
No result is returned.
End Drawing (presumably still from Identify, not measure) is still active.

**Comment by theduckylittle** [comment]
PR available, ending drawing should've happened automatically but didn't.

**Comment by elil** [comment]
Looks (technically) fixed but looks like a new problem has cropped up alongside.  

Use Identify to click a few points.
Switch to measure. (notice that Draw Line, Draw Polygon, and Select from are not engaged)
Do nothing.
Switch to Identify. (notice that draw point is engaged)
Click around the map and no points are registered. 
Click Go since maybe that will make this Go again. 
Identify service seems hung (and no result is returned).

**Comment by theduckylittle** [comment]
I think PR #117 Fixes this as well.

**Comment by elil** [comment]
Looks good!
